In [1]:
#2021.10.13. WED
#Team_SmokeFree

## Data Preprocessing, BG_DONG → HJ_DONG
#00. 패키지 호출하기.
import pandas as pd 
import numpy as np 

#01. kakao_api_key.txt 파일 부르기. 
with open("A:/Python_Project/Team_SmokeFree/key/kakao_api_key.txt",mode="r") as key_file :
    kakao_api_key = key_file.read()

#02. 법정동을 행정동으로 변환하기. 
#(1) 데이터셋 불러오기. 
bus_data = pd.read_excel('../data/서울특별시_버스_pp.xlsx')
dong_data = pd.read_excel('../data/서울특별시_행정동_법정동_코드.xlsx')

#(2) 처리 결과 확인하기. 
bus_data

,자치구,행정동_코드,행정동,법정동,정거장_이름,소재지도로명주소,소재지지번주소,위도,경도
0,종로구,NaN,NaN,종로2가,종로2가사거리,NaN,NaN,37.569764,126.987786
1,종로구,NaN,NaN,와룡동,창경궁.서울대학교병원,NaN,NaN,37.579179,126.996520
2,종로구,NaN,NaN,명륜4가,명륜3가.성대입구,NaN,NaN,37.582709,126.998290
3,종로구,NaN,NaN,관철동,종로2가.삼일교,NaN,NaN,37.568582,126.987507
4,종로구,NaN,NaN,혜화동,혜화동로터리.여운형활동터,NaN,NaN,37.586230,127.001694
...,...,...,...,...,...,...,...,...,...
10901,강동구,NaN,NaN,천호동,우성아파트,NaN,NaN,37.550442,127.139326
10902,강동구,NaN,NaN,암사동,우성아파트,NaN,NaN,37.550620,127.140052
10903,강동구,NaN,NaN,성내동,조일약국,NaN,NaN,37.533686,127.123477
10904,강동구,NaN,NaN,성내동,성내시장,NaN,NaN,37.536199,127.125410
10905,강동구,NaN,NaN,천호동,천호우체국.로데오거리,NaN,NaN,37.540390,127.127353

In [2]:
dong_data

       시도명 시군구명    행정동       행정동코드  법정동       법정동코드
0    서울특별시  종로구    NaN  1111000000  종로구  1111000000
1    서울특별시  종로구  청운효자동  1111051500  청운동  1111010100
2    서울특별시  종로구  청운효자동  1111051500  신교동  1111010200
3    서울특별시  종로구  청운효자동  1111051500  궁정동  1111010300
4    서울특별시  종로구  청운효자동  1111051500  효자동  1111010400
..     ...  ...    ...         ...  ...         ...
763  서울특별시  강동구  성내제2동  1174065000  성내동  1174010800
764  서울특별시  강동구  성내제3동  1174066000  성내동  1174010800
765  서울특별시  강동구     길동  1174068500   길동  1174010500
766  서울특별시  강동구  둔촌제1동  1174069000  둔촌동  1174010600
767  서울특별시  강동구  둔촌제2동  1174070000  둔촌동  1174010600

[768 rows x 6 columns]

In [4]:
#03. 
#(1) 법정동 무결성 검사하기. 
bus_data['IS_GOOD_BGD'] = np.nan
for i in range(len(bus_data))                          :
    for k in range(len(dong_data))                     :
        if bus_data.iloc[i, 3] == dong_data.iloc[k, 4] : 
            bus_data.iloc[i, 9] = 'YES'

#(2) 처리 결과 확인하기. 
bus_data

,자치구,행정동_코드,행정동,법정동,정거장_이름,소재지도로명주소,소재지지번주소,위도,경도,IS_GOOD_BGD
0,종로구,NaN,NaN,종로2가,종로2가사거리,NaN,NaN,37.569764,126.987786,YES
1,종로구,NaN,NaN,와룡동,창경궁.서울대학교병원,NaN,NaN,37.579179,126.996520,YES
2,종로구,NaN,NaN,명륜4가,명륜3가.성대입구,NaN,NaN,37.582709,126.998290,YES
3,종로구,NaN,NaN,관철동,종로2가.삼일교,NaN,NaN,37.568582,126.987507,YES
4,종로구,NaN,NaN,혜화동,혜화동로터리.여운형활동터,NaN,NaN,37.586230,127.001694,YES
...,...,...,...,...,...,...,...,...,...,...
10901,강동구,NaN,NaN,천호동,우성아파트,NaN,NaN,37.550442,127.139326,YES
10902,강동구,NaN,NaN,암사동,우성아파트,NaN,NaN,37.550620,127.140052,YES
10903,강동구,NaN,NaN,성내동,조일약국,NaN,NaN,37.533686,127.123477,YES
10904,강동구,NaN,NaN,성내동,성내시장,NaN,NaN,37.536199,127.125410,YES
10905,강동구,NaN,NaN,천호동,천호우체국.로데오거리,NaN,NaN,37.540390,127.127353,YES

In [6]:
#(3) IS_GOOD_BGD 컬럼에 NO 값 있는지 파악하기. 
bus_data['IS_GOOD_BGD'].value_counts()

YES    10900
Name: IS_GOOD_BGD, dtype: int64

In [8]:
#(4) IS_GOOD_BGD 컬럼 삭제하기. 
bus_data.drop(['IS_GOOD_BGD'], axis=1, inplace=True)

#(5) 처리 결과 확인하기. 
bus_data

,자치구,행정동_코드,행정동,법정동,정거장_이름,소재지도로명주소,소재지지번주소,위도,경도
0,종로구,NaN,NaN,종로2가,종로2가사거리,NaN,NaN,37.569764,126.987786
1,종로구,NaN,NaN,와룡동,창경궁.서울대학교병원,NaN,NaN,37.579179,126.996520
2,종로구,NaN,NaN,명륜4가,명륜3가.성대입구,NaN,NaN,37.582709,126.998290
3,종로구,NaN,NaN,관철동,종로2가.삼일교,NaN,NaN,37.568582,126.987507
4,종로구,NaN,NaN,혜화동,혜화동로터리.여운형활동터,NaN,NaN,37.586230,127.001694
...,...,...,...,...,...,...,...,...,...
10901,강동구,NaN,NaN,천호동,우성아파트,NaN,NaN,37.550442,127.139326
10902,강동구,NaN,NaN,암사동,우성아파트,NaN,NaN,37.550620,127.140052
10903,강동구,NaN,NaN,성내동,조일약국,NaN,NaN,37.533686,127.123477
10904,강동구,NaN,NaN,성내동,성내시장,NaN,NaN,37.536199,127.125410
10905,강동구,NaN,NaN,천호동,천호우체국.로데오거리,NaN,NaN,37.540390,127.127353

In [9]:
#(6) 법정동 값을 기반으로 행정동 및 행정동_코드 변환하기. 
for i in range(len(bus_data))                          :
    for k in range(len(dong_data))                     :
        if bus_data.iloc[i, 3] == dong_data.iloc[k, 4] : 
            bus_data.iloc[i, 2] = dong_data.iloc[k, 2]
            bus_data.iloc[i, 1] = dong_data.iloc[k, 3]

#(7) 처리 결과 확인하기. 
bus_data

,자치구,행정동_코드,행정동,법정동,정거장_이름,소재지도로명주소,소재지지번주소,위도,경도
0,종로구,1.111062e+09,종로1.2.3.4가동,종로2가,종로2가사거리,NaN,NaN,37.569764,126.987786
1,종로구,1.111065e+09,혜화동,와룡동,창경궁.서울대학교병원,NaN,NaN,37.579179,126.996520
2,종로구,1.111065e+09,혜화동,명륜4가,명륜3가.성대입구,NaN,NaN,37.582709,126.998290
3,종로구,1.111062e+09,종로1.2.3.4가동,관철동,종로2가.삼일교,NaN,NaN,37.568582,126.987507
4,종로구,1.111065e+09,혜화동,혜화동,혜화동로터리.여운형활동터,NaN,NaN,37.586230,127.001694
...,...,...,...,...,...,...,...,...,...
10901,강동구,1.174062e+09,천호제3동,천호동,우성아파트,NaN,NaN,37.550442,127.139326
10902,강동구,1.174059e+09,암사제3동,암사동,우성아파트,NaN,NaN,37.550620,127.140052
10903,강동구,1.174066e+09,성내제3동,성내동,조일약국,NaN,NaN,37.533686,127.123477
10904,강동구,1.174066e+09,성내제3동,성내동,성내시장,NaN,NaN,37.536199,127.125410
10905,강동구,1.174062e+09,천호제3동,천호동,천호우체국.로데오거리,NaN,NaN,37.540390,127.127353

In [10]:
#(8) 법정동 컬럼 삭제하기.
bus_data.drop(['법정동'], axis=1, inplace=True)

#(9) 처리 결과 확인하기. 
bus_data

,자치구,행정동_코드,행정동,정거장_이름,소재지도로명주소,소재지지번주소,위도,경도
0,종로구,1.111062e+09,종로1.2.3.4가동,종로2가사거리,NaN,NaN,37.569764,126.987786
1,종로구,1.111065e+09,혜화동,창경궁.서울대학교병원,NaN,NaN,37.579179,126.996520
2,종로구,1.111065e+09,혜화동,명륜3가.성대입구,NaN,NaN,37.582709,126.998290
3,종로구,1.111062e+09,종로1.2.3.4가동,종로2가.삼일교,NaN,NaN,37.568582,126.987507
4,종로구,1.111065e+09,혜화동,혜화동로터리.여운형활동터,NaN,NaN,37.586230,127.001694
...,...,...,...,...,...,...,...,...
10901,강동구,1.174062e+09,천호제3동,우성아파트,NaN,NaN,37.550442,127.139326
10902,강동구,1.174059e+09,암사제3동,우성아파트,NaN,NaN,37.550620,127.140052
10903,강동구,1.174066e+09,성내제3동,조일약국,NaN,NaN,37.533686,127.123477
10904,강동구,1.174066e+09,성내제3동,성내시장,NaN,NaN,37.536199,127.125410
10905,강동구,1.174062e+09,천호제3동,천호우체국.로데오거리,NaN,NaN,37.540390,127.127353

In [11]:
#(10) 처리 결과 저장하기.
bus_data.to_excel('temp_file.xlsx', index=False)