In [35]:
#2021.10.13. WED
#Team_SmokeFree

## Data Preprocessing, X, Y -> GU, HGDONG_CODE, HGDONG
#00. 패키지 호출하기.
import warnings
import pandas as pd 
import numpy as np 
import requests

#00-1. warning message ignore 
warnings.filterwarnings(action='ignore')

#01. kakao_api_key.txt 파일 부르기. 
with open("A:/Python_Project/Team_SmokeFree/key/kakao_api_key.txt",mode="r") as key_file :
    kakao_api_key = key_file.read()

#02. 법정동을 행정동으로 변환하기. 
#(1) 데이터셋 불러오기. 
SS_data = pd.read_excel('../data/01_Feature_Data/서울특별시_담배소매업_pp.xlsx')
dong_data = pd.read_excel('../data/서울특별시_행정동_법정동_코드.xlsx')

#(2) 처리 결과 확인하기. 
SS_data

,INDEX,자치구,행정동_코드,행정동,사업장명,소재지_지번_주소,소재지_도로명_주소,위도,경도
0,0,금천구,1.154571e+09,시흥제5동,지에스25 금천다온,서울특별시 금천구 시흥동 923번지,서울특별시 금천구 독산로6가길 18 1층 일부호 (시흥동),37.448859,126.905963
1,1,용산구,1.117062e+09,한강로동,씨유 선인상가점,NaN,서울특별시 용산구 새창로 181 21동 2018호 (한강로2가 선인상가),37.532717,126.965178
2,2,동대문구,1.123070e+09,청량리동,지에스(GS)25영휘원점,서울특별시 동대문구 청량리동 199번지 121호,서울특별시 동대문구 홍릉로 78-1 (청량리동),37.587201,127.043224
3,3,동작구,1.159065e+09,사당제5동,이마트24동작골든포레점,서울특별시 동작구 사당동 181번지 사당 롯데캐슬 골든포레,서울특별시 동작구 사당로 90 상가1동 105호 (사당동 사당 롯데캐슬 골든포레),37.492336,126.962448
4,4,광진구,1.121574e+09,중곡제1동,지에스25 중곡희망점,NaN,서울특별시 광진구 동일로68길 49 1층 (중곡동 월드빌),37.562168,127.078546
...,...,...,...,...,...,...,...,...,...
20458,20458,강북구,1.130554e+09,NaN,씨유 강북오패산로점,서울특별시 강북구 미아동 245-32,서울특별시 강북구 오패산로 271 1층 (미아동),37.625541,127.029678
20459,20459,강서구,1.150054e+09,NaN,GS25 신월초교점,서울특별시 강서구 화곡동 1081-7,서울특별시 강서구 화곡로24길 14(화곡동),37.540314,126.838198
20460,20460,은평구,1.138062e+09,NaN,럭키스토어,서울특별시 은평구 역촌동 2-38 SM 벨리체,서울특별시 은평구 서오릉로 107 1층 104호 (역촌동 SM 벨리체),37.609286,126.919912
20461,20461,동대문구,1.123065e+09,NaN,온오프,서울특별시 동대문구 장안동 414-8,서울특별시 동대문구 천호대로 365(장안동),37.562558,127.059736
20462,20462,성동구,1.120069e+09,NaN,세븐일레븐 서울숲SKV1점,서울특별시 성동구 성수동2가 284번지 55호,서울특별시 성동구 성수일로8길 5 1층 107호 (성수동2가 서울숲SKV1),37.547075,127.051616

In [36]:
dong_data

       시도명 시군구명       행정동코드    행정동       법정동코드  법정동
0    서울특별시  종로구  1111000000    NaN  1111000000  종로구
1    서울특별시  종로구  1111051500  청운효자동  1111010100  청운동
2    서울특별시  종로구  1111051500  청운효자동  1111010200  신교동
3    서울특별시  종로구  1111051500  청운효자동  1111010300  궁정동
4    서울특별시  종로구  1111051500  청운효자동  1111010400  효자동
..     ...  ...         ...    ...         ...  ...
763  서울특별시  강동구  1174065000  성내제2동  1174010800  성내동
764  서울특별시  강동구  1174066000  성내제3동  1174010800  성내동
765  서울특별시  강동구  1174068500     길동  1174010500   길동
766  서울특별시  강동구  1174069000  둔촌제1동  1174010600  둔촌동
767  서울특별시  강동구  1174070000  둔촌제2동  1174010600  둔촌동

[768 rows x 6 columns]

In [37]:
#(4) 구가 없는 행 추출하기. 
SS_data_no_HGD = SS_data[SS_data['자치구']=='ERROR']

#(5) 결과 확인하기. 
SS_data_no_HGD

,INDEX,자치구,행정동_코드,행정동,사업장명,소재지_지번_주소,소재지_도로명_주소,위도,경도
13,13,ERROR,0.0,NaN,밀크마트,서울특별시 종로구 창신동 536번지,NaN,37.575396,127.012431
21,21,ERROR,0.0,NaN,지은전업사,서울특별시 종로구 무악동 45번지 82호,서울특별시 종로구 통일로14길 16 (무악동),37.575208,126.957913
24,24,ERROR,0.0,NaN,은호주단,서울특별시 종로구 종로5가 398호,NaN,37.5706031,127.003511
25,25,ERROR,0.0,NaN,GS25 숭인본점,서울특별시 종로구 숭인1동 1417 삼신빌딩 1층,NaN,37.5737187,127.021985
27,27,ERROR,0.0,NaN,훼미리마트신문로점,서울특별시 종로구 신문로2가 89번지 2호,NaN,37.5708510,126.969201
...,...,...,...,...,...,...,...,...,...
19763,19763,ERROR,0.0,NaN,(주)뚝섬현대유통,서울특별시 성동구 성수동1가 102번지 2호,NaN,37.5391767,127.046993
19847,19847,ERROR,0.0,NaN,홈플러스(주) 익스프레스 면목점,서울특별시 중랑구 면목동 499번지 4호,NaN,37.5839779,127.088117
20254,20254,ERROR,0.0,NaN,.,서울특별시 종로구 동숭동 121-1,NaN,37.5813879,127.004858
20402,20402,ERROR,0.0,NaN,GS25성북중앙점,서울특별시 성북구 종암동 83번지 3호,서울특별시 성북구 종암로21길 37-6 (종암동),37.6005837,127.033090
20410,20410,ERROR,0.0,NaN,씨유 상봉두꺼비점,서울특별시 중랑구 면목동 131번지 6호 2통 1반,NaN,37.5920253,127.085941

In [38]:
#03. API 이용하여 정보 추출하기. 
#(1) 주소지를 기반으로 행정동 코드, 경도, 위도 추출하여 데이터프레임에 기입하기. 
SS_data_no_HGD_x       = SS_data_no_HGD['경도'].values
SS_data_no_HGD_y       = SS_data_no_HGD['위도'].values
SS_data_no_HGD_자치구      = []
SS_data_no_HGD_행정동_코드 = []

local_url = "https://dapi.kakao.com/v2/local/geo/coord2regioncode.json"
for num in range(len(SS_data_no_HGD_x))                                                             :
    try                                                                                             :
        x = SS_data_no_HGD_x[num]
        y = SS_data_no_HGD_y[num]   
        url=f'{local_url}?x={x}&y={y}&input_coord=WGS84' 
    except Exception                                                                                :
        x = SS_data_no_HGD_x[num]
        y = SS_data_no_HGD_y[num]      
        url=f'{local_url}?x={x}&y={y}&input_coord=WGS84' 
    try                                                                                             : 
        REQ_RESULT = requests.get(url, headers={"Authorization":f"KakaoAK {kakao_api_key}"}).json()
        SS_data_no_HGD_자치구.append(REQ_RESULT['documents'][1]['region_2depth_name'])
        SS_data_no_HGD_행정동_코드.append(REQ_RESULT['documents'][1]['code'])
        #print(f'DONE ! index_num = {num}')
    except Exception                                                                                :
        try                                                                                         :
            x = SS_data_no_HGD_x[num]
            y = SS_data_no_HGD_y[num]   
            url=f'{local_url}?x={x}&y={y}&input_coord=WGS84' 
            REQ_RESULT = requests.get(url, headers={"Authorization":f"KakaoAK {kakao_api_key}"}).json()
            SS_data_no_HGD_자치구.append(REQ_RESULT['documents'][1]['region_2depth_name'])
            SS_data_no_HGD_행정동_코드.append(REQ_RESULT['documents'][1]['code'])
            #print(f'DONE ! index_num = {num}')
        except Exception                                                                            :
            SS_data_no_HGD_자치구.append('ERROR')
            SS_data_no_HGD_행정동_코드.append(0)
            #print(f'ERROR ! index_num = {num}')

#(2) 처리 결과 저장하기. 
SS_data_no_HGD = pd.DataFrame({
    'INDEX'              : SS_data_no_HGD['INDEX'].values,
    '자치구'             : SS_data_no_HGD_자치구,
    '행정동_코드'        : SS_data_no_HGD_행정동_코드,
    '행정동'             : SS_data_no_HGD['행정동'].values,
    '사업장명'           : SS_data_no_HGD['사업장명'].values,
    '소재지_지번_주소'   : SS_data_no_HGD['소재지_지번_주소'].values,
    '소재지_도로명_주소' : SS_data_no_HGD['소재지_도로명_주소'].values,
    '위도'               : SS_data_no_HGD['위도'].values, 
    '경도'               : SS_data_no_HGD['경도'].values
})

#(3) 처리 결과 확인하기. 
SS_data_no_HGD

,INDEX,자치구,행정동_코드,행정동,사업장명,소재지_지번_주소,소재지_도로명_주소,위도,경도
0,13,종로구,1111068000,NaN,밀크마트,서울특별시 종로구 창신동 536번지,NaN,37.575396,127.012431
1,21,종로구,1111057000,NaN,지은전업사,서울특별시 종로구 무악동 45번지 82호,서울특별시 종로구 통일로14길 16 (무악동),37.575208,126.957913
2,24,종로구,1111063000,NaN,은호주단,서울특별시 종로구 종로5가 398호,NaN,37.5706031,127.003511
3,25,종로구,1111071000,NaN,GS25 숭인본점,서울특별시 종로구 숭인1동 1417 삼신빌딩 1층,NaN,37.5737187,127.021985
4,27,종로구,1111053000,NaN,훼미리마트신문로점,서울특별시 종로구 신문로2가 89번지 2호,NaN,37.5708510,126.969201
...,...,...,...,...,...,...,...,...,...
1193,19763,성동구,1120065000,NaN,(주)뚝섬현대유통,서울특별시 성동구 성수동1가 102번지 2호,NaN,37.5391767,127.046993
1194,19847,중랑구,1126057500,NaN,홈플러스(주) 익스프레스 면목점,서울특별시 중랑구 면목동 499번지 4호,NaN,37.5839779,127.088117
1195,20254,종로구,1111064000,NaN,.,서울특별시 종로구 동숭동 121-1,NaN,37.5813879,127.004858
1196,20402,성북구,1129070500,NaN,GS25성북중앙점,서울특별시 성북구 종암동 83번지 3호,서울특별시 성북구 종암로21길 37-6 (종암동),37.6005837,127.033090
1197,20410,중랑구,1126052000,NaN,씨유 상봉두꺼비점,서울특별시 중랑구 면목동 131번지 6호 2통 1반,NaN,37.5920253,127.085941

In [40]:
#(4) 인덱스 기반 매칭하기.
for i in range(len(SS_data)) :
    for k in range(len(SS_data_no_HGD)) :
        if SS_data['INDEX'][i] == SS_data_no_HGD['INDEX'][k] :
            SS_data['자치구'][i] = SS_data_no_HGD['자치구'][k]
            SS_data['행정동_코드'][i] = SS_data_no_HGD['행정동_코드'][k]

#(5) 처리 결과 확인하기.    
SS_data

,INDEX,자치구,행정동_코드,행정동,사업장명,소재지_지번_주소,소재지_도로명_주소,위도,경도
0,0,금천구,1.154571e+09,시흥제5동,지에스25 금천다온,서울특별시 금천구 시흥동 923번지,서울특별시 금천구 독산로6가길 18 1층 일부호 (시흥동),37.448859,126.905963
1,1,용산구,1.117062e+09,한강로동,씨유 선인상가점,NaN,서울특별시 용산구 새창로 181 21동 2018호 (한강로2가 선인상가),37.532717,126.965178
2,2,동대문구,1.123070e+09,청량리동,지에스(GS)25영휘원점,서울특별시 동대문구 청량리동 199번지 121호,서울특별시 동대문구 홍릉로 78-1 (청량리동),37.587201,127.043224
3,3,동작구,1.159065e+09,사당제5동,이마트24동작골든포레점,서울특별시 동작구 사당동 181번지 사당 롯데캐슬 골든포레,서울특별시 동작구 사당로 90 상가1동 105호 (사당동 사당 롯데캐슬 골든포레),37.492336,126.962448
4,4,광진구,1.121574e+09,중곡제1동,지에스25 중곡희망점,NaN,서울특별시 광진구 동일로68길 49 1층 (중곡동 월드빌),37.562168,127.078546
...,...,...,...,...,...,...,...,...,...
20458,20458,강북구,1.130554e+09,NaN,씨유 강북오패산로점,서울특별시 강북구 미아동 245-32,서울특별시 강북구 오패산로 271 1층 (미아동),37.625541,127.029678
20459,20459,강서구,1.150054e+09,NaN,GS25 신월초교점,서울특별시 강서구 화곡동 1081-7,서울특별시 강서구 화곡로24길 14(화곡동),37.540314,126.838198
20460,20460,은평구,1.138062e+09,NaN,럭키스토어,서울특별시 은평구 역촌동 2-38 SM 벨리체,서울특별시 은평구 서오릉로 107 1층 104호 (역촌동 SM 벨리체),37.609286,126.919912
20461,20461,동대문구,1.123065e+09,NaN,온오프,서울특별시 동대문구 장안동 414-8,서울특별시 동대문구 천호대로 365(장안동),37.562558,127.059736
20462,20462,성동구,1.120069e+09,NaN,세븐일레븐 서울숲SKV1점,서울특별시 성동구 성수동2가 284번지 55호,서울특별시 성동구 성수일로8길 5 1층 107호 (성수동2가 서울숲SKV1),37.547075,127.051616

In [41]:
#04. 행정동 코드를 기반으로 행정동 값 매칭하기. 
#(1) FOR-LOOP 사용하기.
for i in range(len(SS_data))                                       :
    for k in range(len(dong_data))                                 :
        if SS_data['행정동_코드'][i] == dong_data['행정동코드'][k] : 
            SS_data['행정동'][i] = dong_data['행정동'][k]
            break

#(2) 처리 결과 확인하기. 
SS_data

,INDEX,자치구,행정동_코드,행정동,사업장명,소재지_지번_주소,소재지_도로명_주소,위도,경도
0,0,금천구,1.154571e+09,시흥제5동,지에스25 금천다온,서울특별시 금천구 시흥동 923번지,서울특별시 금천구 독산로6가길 18 1층 일부호 (시흥동),37.448859,126.905963
1,1,용산구,1.117062e+09,한강로동,씨유 선인상가점,NaN,서울특별시 용산구 새창로 181 21동 2018호 (한강로2가 선인상가),37.532717,126.965178
2,2,동대문구,1.123070e+09,청량리동,지에스(GS)25영휘원점,서울특별시 동대문구 청량리동 199번지 121호,서울특별시 동대문구 홍릉로 78-1 (청량리동),37.587201,127.043224
3,3,동작구,1.159065e+09,사당제5동,이마트24동작골든포레점,서울특별시 동작구 사당동 181번지 사당 롯데캐슬 골든포레,서울특별시 동작구 사당로 90 상가1동 105호 (사당동 사당 롯데캐슬 골든포레),37.492336,126.962448
4,4,광진구,1.121574e+09,중곡제1동,지에스25 중곡희망점,NaN,서울특별시 광진구 동일로68길 49 1층 (중곡동 월드빌),37.562168,127.078546
...,...,...,...,...,...,...,...,...,...
20458,20458,강북구,1.130554e+09,미아동,씨유 강북오패산로점,서울특별시 강북구 미아동 245-32,서울특별시 강북구 오패산로 271 1층 (미아동),37.625541,127.029678
20459,20459,강서구,1.150054e+09,화곡제1동,GS25 신월초교점,서울특별시 강서구 화곡동 1081-7,서울특별시 강서구 화곡로24길 14(화곡동),37.540314,126.838198
20460,20460,은평구,1.138062e+09,역촌동,럭키스토어,서울특별시 은평구 역촌동 2-38 SM 벨리체,서울특별시 은평구 서오릉로 107 1층 104호 (역촌동 SM 벨리체),37.609286,126.919912
20461,20461,동대문구,1.123065e+09,장안제1동,온오프,서울특별시 동대문구 장안동 414-8,서울특별시 동대문구 천호대로 365(장안동),37.562558,127.059736
20462,20462,성동구,1.120069e+09,성수2가제3동,세븐일레븐 서울숲SKV1점,서울특별시 성동구 성수동2가 284번지 55호,서울특별시 성동구 성수일로8길 5 1층 107호 (성수동2가 서울숲SKV1),37.547075,127.051616

In [42]:
#(3) 처리 결과 저장하기.
SS_data.to_excel('temp_file.xlsx', index=False)