In [1]:
#2021.10.20. TUE
#Team_SmokeFree

## SCORE CALCULATION FOR MCLP
#00. 패키지 호출하기. 
import warnings
import re
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import MinMaxScaler

#00-1. warning message ignore 
warnings.filterwarnings(action='ignore')

In [2]:
#01. 데이터셋 전처리하기. 
#(1) RANDOM_POINT 데이터셋 불러오기. 
RANDOM_POINT = pd.read_excel('../data/RANDOM_POINT_DATASET_pp.xlsx')

#(2) 세대 컬럼 스케일링 처리하기. 
scaler = MinMaxScaler()
세대_scaler = scaler.fit_transform(RANDOM_POINT[['세대_COUNT']])

#(3) 값 컬럼 변경하기. 
RANDOM_POINT['세대_COUNT'] = 세대_scaler

#(4) 처리 결과 확인하기. 
RANDOM_POINT

,rand_point,자치구,행정동_코드,행정동,세대_COUNT,노래연습장_COUNT,당구장_COUNT,PC방_COUNT,금연구역_10m_COUNT,금연구역_50m_COUNT,음식점_외식_COUNT,음식점_회식_COUNT,음식점_카페_COUNT,위도,경도,geometry
0,0,금천구,1154568000,시흥제2동,0.250891,1,0,0,2,1,9,3,1,37.449962,126.913406,POINT (192337.7432523154 438954.0766042818)
1,1,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,11,4,1,37.449964,126.914394,POINT (192425.2336731556 438954.2123132667)
2,2,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,11,4,1,37.449939,126.914258,POINT (192413.1979568179 438951.4329210447)
3,3,금천구,1154568000,시흥제2동,0.250891,2,0,0,2,1,9,4,1,37.449956,126.913289,POINT (192327.4056526743 438953.4538745985)
4,4,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,12,4,1,37.450008,126.913638,POINT (192358.2717906134 438959.210054699)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40286,41191,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.499947,126.953611,POINT (195897.9891959261 444499.2420208962)
40287,41192,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.500272,126.953683,POINT (195904.4341447904 444535.2696354929)
40288,41193,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.500105,126.953733,POINT (195908.8060317755 444516.8050831873)
40289,41194,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,1,0,0,37.500540,126.953708,POINT (195906.6493213855 444565.0878704682)
40290,41195,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.499826,126.953583,POINT (195895.5612148321 444485.8452144368)

In [3]:
#(5) SHAP Value 데이터셋 불러오기.
SHAP_VAL = pd.read_excel('../data/SHAP_values_dong.xlsx')

#(6) 처리 결과 확인하기.
SHAP_VAL

,행정동_코드,행정동,세대,노래연습장,당구장,PC방,금연구역_10m,금연구역_50m,음식점_외식,음식점_회식,음식점_카페
0,1171063100,가락1동,2.597895,-0.543748,3.325141,7.194775,-0.786023,2.121663,-21.166832,3.484164,0.289485
1,1171063200,가락2동,19.447301,3.531995,-2.902738,-2.953587,-1.925279,1.004377,1.017861,4.509757,0.846309
2,1171062000,가락본동,-5.109760,11.354683,3.083922,-1.364136,5.060548,-1.755528,41.061920,0.603275,-0.008842
3,1153059500,가리봉동,13.575740,8.590204,-5.402833,-2.642563,7.951847,-0.325688,48.876958,-6.381114,0.603056
4,1154551000,가산동,-27.700646,1.911541,1.465872,-0.153733,0.699950,1.260090,23.791659,0.545698,0.412044
...,...,...,...,...,...,...,...,...,...,...,...
419,1117058000,효창동,-11.647341,-1.532828,-1.033294,4.711256,-0.620750,-2.006127,-26.066835,1.748712,1.855414
420,1117051000,후암동,27.822540,-3.551473,-5.373569,0.209138,-4.905190,0.497515,21.998067,2.671751,-2.144422
421,1123072000,휘경제1동,5.479156,0.914973,0.042831,0.825690,3.453579,0.548212,-23.843397,1.595402,0.854290
422,1123073000,휘경제2동,45.237879,-3.438942,-5.453401,0.296867,0.190012,-3.168339,-23.628410,3.837766,2.349718
423,1159060500,흑석동,-16.191242,-3.477857,-3.583747,-2.523209,2.624963,-3.133126,-25.946360,1.590373,2.599921

In [4]:
#(7) BETA 계수 계산하기. 
BETA_VAL = pd.DataFrame({
    '세대'         : 254.41,
    '노래연습장'   : 81.15, 
    '당구장'       : 27.72, 
    'PC방'         : -48.01, 
    '금연구역_10m' : 38.89, 
    '금연구역_50m' : -41.05, 
    '음식점_외식'  : 264.28, 
    '음식점_회식'  : -45.1, 
    '음식점_카페'  : 74.67 
}, index=[0])

#(8) 처리 결과 확인하기.
BETA_VAL

       세대  노래연습장    당구장    PC방  금연구역_10m  금연구역_50m  음식점_외식  음식점_회식  음식점_카페
0  254.41  81.15  27.72 -48.01     38.89    -41.05  264.28   -45.1   74.67

In [5]:
#02. SCORE_b 계산하기. 
#(1) 처리하기. 
RANDOM_POINT['SCORE_b'] = 0

for i in range(len(RANDOM_POINT)) :
    세대_val         = RANDOM_POINT['세대_COUNT'][i] * BETA_VAL['세대'][0]
    노래연습장_val   = RANDOM_POINT['노래연습장_COUNT'][i] * BETA_VAL['노래연습장'][0]
    당구장_val       = RANDOM_POINT['당구장_COUNT'][i] * BETA_VAL['당구장'][0]
    PC방_val         = RANDOM_POINT['PC방_COUNT'][i] * BETA_VAL['PC방'][0]
    금연구역_10m_val = RANDOM_POINT['금연구역_10m_COUNT'][i] * BETA_VAL['금연구역_10m'][0]
    금연구역_50m_val = RANDOM_POINT['금연구역_50m_COUNT'][i] * BETA_VAL['금연구역_50m'][0]
    음식점_외식_val  = RANDOM_POINT['음식점_외식_COUNT'][i] * BETA_VAL['음식점_외식'][0]
    음식점_회식_val  = RANDOM_POINT['음식점_회식_COUNT'][i] * BETA_VAL['음식점_회식'][0]
    음식점_카페_val  = RANDOM_POINT['음식점_카페_COUNT'][i] * BETA_VAL['음식점_카페'][0]
    BETA_SUM         = 세대_val + 노래연습장_val + 당구장_val + PC방_val + 금연구역_10m_val + 금연구역_50m_val + 음식점_외식_val + 음식점_회식_val + 음식점_카페_val

    RANDOM_POINT['SCORE_b'][i] = BETA_SUM
    print(f'DONE ! INDEX_NUM = {i}')

DONE ! INDEX_NUM = 0
DONE ! INDEX_NUM = 1
DONE ! INDEX_NUM = 2
DONE ! INDEX_NUM = 3
DONE ! INDEX_NUM = 4
DONE ! INDEX_NUM = 5
DONE ! INDEX_NUM = 6
DONE ! INDEX_NUM = 7
DONE ! INDEX_NUM = 8
DONE ! INDEX_NUM = 9
DONE ! INDEX_NUM = 10
DONE ! INDEX_NUM = 11
DONE ! INDEX_NUM = 12
DONE ! INDEX_NUM = 13
DONE ! INDEX_NUM = 14
DONE ! INDEX_NUM = 15
DONE ! INDEX_NUM = 16
DONE ! INDEX_NUM = 17
DONE ! INDEX_NUM = 18
DONE ! INDEX_NUM = 19
DONE ! INDEX_NUM = 20
DONE ! INDEX_NUM = 21
DONE ! INDEX_NUM = 22
DONE ! INDEX_NUM = 23
DONE ! INDEX_NUM = 24
DONE ! INDEX_NUM = 25
DONE ! INDEX_NUM = 26
DONE ! INDEX_NUM = 27
DONE ! INDEX_NUM = 28
DONE ! INDEX_NUM = 29
DONE ! INDEX_NUM = 30
DONE ! INDEX_NUM = 31
DONE ! INDEX_NUM = 32
DONE ! INDEX_NUM = 33
DONE ! INDEX_NUM = 34
DONE ! INDEX_NUM = 35
DONE ! INDEX_NUM = 36
DONE ! INDEX_NUM = 37
DONE ! INDEX_NUM = 38
DONE ! INDEX_NUM = 39
DONE ! INDEX_NUM = 40
DONE ! INDEX_NUM = 41
DONE ! INDEX_NUM = 42
DONE ! INDEX_NUM = 43
DONE ! INDEX_NUM = 44
DONE ! INDEX_NUM = 45
DONE ! INDEX_NUM = 46
DONE ! INDEX_NUM = 47
DONE ! INDEX_NUM = 48
DONE ! INDEX_NUM = 49
DONE ! INDEX_NUM = 50
DONE ! INDEX_NUM = 51
DONE ! INDEX_NUM = 52
DONE ! INDEX_NUM = 53
DONE ! INDEX_NUM = 54
DONE ! INDEX_NUM = 55
DONE ! INDEX_NUM = 56
DONE ! INDEX_NUM = 57
DONE ! INDEX_NUM = 58
DONE ! INDEX_NUM = 59
DONE ! INDEX_NUM = 60
DONE ! INDEX_NUM = 61
DONE ! INDEX_NUM = 62
DONE ! INDEX_NUM = 63
DONE ! INDEX_NUM = 64
DONE ! INDEX_NUM = 65
DONE ! INDEX_NUM = 66
DONE ! INDEX_NUM = 67
DONE ! INDEX_NUM = 68
DONE ! INDEX_NUM = 69
DONE ! INDEX_NUM = 70
DONE ! INDEX_NUM = 71
DONE ! INDEX_NUM = 72
DONE ! INDEX_NUM = 73
DONE ! INDEX_NUM = 74
DONE ! INDEX_NUM = 75
DONE ! INDEX_NUM = 76
DONE ! INDEX_NUM = 77
DONE ! INDEX_NUM = 78
DONE ! INDEX_NUM = 79
DONE ! INDEX_NUM = 80
DONE ! INDEX_NUM = 81
DONE ! INDEX_NUM = 82
DONE ! INDEX_NUM = 83
DONE ! INDEX_NUM = 84
DONE ! INDEX_NUM = 85
DONE ! INDEX_NUM = 86
DONE ! INDEX_NUM = 87
DONE ! INDEX_NUM = 88
DONE ! INDEX_NUM = 89
DONE ! INDEX_NUM = 90
DONE ! INDEX_NUM = 91
DONE ! INDEX_NUM = 92
DONE ! INDEX_NUM = 93
DONE ! INDEX_NUM = 94
DONE ! INDEX_NUM = 95
DONE ! INDEX_NUM = 96
DONE ! INDEX_NUM = 97
DONE ! INDEX_NUM = 98
DONE ! INDEX_NUM = 99
DONE ! INDEX_NUM = 100
DONE ! INDEX_NUM = 101
DONE ! INDEX_NUM = 102
DONE ! INDEX_NUM = 103
DONE ! INDEX_NUM = 104
DONE ! INDEX_NUM = 105
DONE ! INDEX_NUM = 106
DONE ! INDEX_NUM = 107
DONE ! INDEX_NUM = 108
DONE ! INDEX_NUM = 109
DONE ! INDEX_NUM = 110
DONE ! INDEX_NUM = 111
DONE ! INDEX_NUM = 112
DONE ! INDEX_NUM = 113
DONE ! INDEX_NUM = 114
DONE ! INDEX_NUM = 115
DONE ! INDEX_NUM = 116
DONE ! INDEX_NUM = 117
DONE ! INDEX_NUM = 118
DONE ! INDEX_NUM = 119
DONE ! INDEX_NUM = 120
DONE ! INDEX_NUM = 121
DONE ! INDEX_NUM = 122
DONE ! INDEX_NUM = 123
DONE ! INDEX_NUM = 124
DONE ! INDEX_NUM = 125
DONE ! INDEX_NUM = 126
DONE ! INDEX_NUM = 127
DONE ! INDEX_NUM = 128
DONE ! INDEX_NUM = 129
DONE ! INDEX_NUM = 130
DONE ! INDEX_NUM = 131
DONE ! INDEX_NUM = 132
DONE ! INDEX_NUM = 133
DONE ! INDEX_NUM = 134
DONE ! INDEX_NUM = 135
DONE ! INDEX_NUM = 136
DONE ! INDEX_NUM = 137
DONE ! INDEX_NUM = 138
DONE ! INDEX_NUM = 139
DONE ! INDEX_NUM = 140
DONE ! INDEX_NUM = 141
DONE ! INDEX_NUM = 142
DONE ! INDEX_NUM = 143
DONE ! INDEX_NUM = 144
DONE ! INDEX_NUM = 145
DONE ! INDEX_NUM = 146
DONE ! INDEX_NUM = 147
DONE ! INDEX_NUM = 148
DONE ! INDEX_NUM = 149
DONE ! INDEX_NUM = 150
DONE ! INDEX_NUM = 151
DONE ! INDEX_NUM = 152
DONE ! INDEX_NUM = 153
DONE ! INDEX_NUM = 154
DONE ! INDEX_NUM = 155
DONE ! INDEX_NUM = 156
DONE ! INDEX_NUM = 157
DONE ! INDEX_NUM = 158
DONE ! INDEX_NUM = 159
DONE ! INDEX_NUM = 160
DONE ! INDEX_NUM = 161
DONE ! INDEX_NUM = 162
DONE ! INDEX_NUM = 163
DONE ! INDEX_NUM = 164
DONE ! INDEX_NUM = 165
DONE ! INDEX_NUM = 166
DONE ! INDEX_NUM = 167
DONE ! INDEX_NUM = 168
DONE ! INDEX_NUM = 169
DONE ! INDEX_NUM = 170
DONE ! INDEX_NUM = 171
DONE ! INDEX_NUM = 172
DONE ! INDEX_NUM = 173
DONE ! INDEX_NUM = 174
DONE ! INDEX_NUM = 175
DONE ! INDEX_NUM = 176
DONE ! INDEX_NUM = 177
DONE ! INDEX_NUM = 178
DONE ! INDEX_NUM = 179
DONE ! INDEX_NUM = 180
DONE ! INDEX_NUM = 181
DONE ! INDEX_NUM = 182
DONE ! INDEX_NUM = 183
DONE ! INDEX_NUM = 184
DONE ! INDEX_NUM = 185
DONE ! INDEX_NUM = 186
DONE ! INDEX_NUM = 187
DONE ! INDEX_NUM = 188
DONE ! INDEX_NUM = 189
DONE ! INDEX_NUM = 190
DONE ! INDEX_NUM = 191
DONE ! INDEX_NUM = 192
DONE ! INDEX_NUM = 193
DONE ! INDEX_NUM = 194
DONE ! INDEX_NUM = 195
DONE ! INDEX_NUM = 196
DONE ! INDEX_NUM = 197
DONE ! INDEX_NUM = 198
DONE ! INDEX_NUM = 199
DONE ! INDEX_NUM = 200
DONE ! INDEX_NUM = 201
DONE ! INDEX_NUM = 202
DONE ! INDEX_NUM = 203
DONE ! INDEX_NUM = 204
DONE ! INDEX_NUM = 205
DONE ! INDEX_NUM = 206
DONE ! INDEX_NUM = 207
DONE ! INDEX_NUM = 208
DONE ! INDEX_NUM = 209
DONE ! INDEX_NUM = 210
DONE ! INDEX_NUM = 211
DONE ! INDEX_NUM = 212
DONE ! INDEX_NUM = 213
DONE ! INDEX_NUM = 214
DONE ! INDEX_NUM = 215
DONE ! INDEX_NUM = 216
DONE ! INDEX_NUM = 217
DONE ! INDEX_NUM = 218
DONE ! INDEX_NUM = 219
DONE ! INDEX_NUM = 220
DONE ! INDEX_NUM = 221
DONE ! INDEX_NUM = 222
DONE ! INDEX_NUM = 223
DONE ! INDEX_NUM = 224
DONE ! INDEX_NUM = 225
DONE ! INDEX_NUM = 226
DONE ! INDEX_NUM = 227
DONE ! INDEX_NUM = 228
DONE ! INDEX_NUM = 229
DONE ! INDEX_NUM = 230
DONE ! INDEX_NUM = 231
DONE ! INDEX_NUM = 232
DONE ! INDEX_NUM = 233
DONE ! INDEX_NUM = 234
DONE ! INDEX_NUM = 235
DONE ! INDEX_NUM = 236
DONE ! INDEX_NUM = 237
DONE ! INDEX_NUM = 238
DONE ! INDEX_NUM = 239
DONE ! INDEX_NUM = 240
DONE ! INDEX_NUM = 241
DONE ! INDEX_NUM = 242
DONE ! INDEX_NUM = 243
DONE ! INDEX_NUM = 244
DONE ! INDEX_NUM = 245
DONE ! INDEX_NUM = 246
DONE ! INDEX_NUM = 247
DONE ! INDEX_NUM = 248
DONE ! INDEX_NUM = 249
DONE ! INDEX_NUM = 250
DONE ! INDEX_NUM = 251
DONE ! INDEX_NUM = 252
DONE ! INDEX_NUM = 253
DONE ! INDEX_NUM = 254
DONE ! INDEX_NUM = 255
DONE ! INDEX_NUM = 256
DONE ! INDEX_NUM = 257
DONE ! INDEX_NUM = 258
DONE ! INDEX_NUM = 259
DONE ! INDEX_NUM = 260
DONE ! INDEX_NUM = 261
DONE ! INDEX_NUM = 262
DONE ! INDEX_NUM = 263
DONE ! INDEX_NUM = 264
DONE ! INDEX_NUM = 265
DONE ! INDEX_NUM = 266
DONE ! INDEX_NUM = 267
DONE ! INDEX_NUM = 268
DONE ! INDEX_NUM = 269
DONE ! INDEX_NUM = 270
DONE ! INDEX_NUM = 271
DONE ! INDEX_NUM = 272
DONE ! INDEX_NUM = 273
DONE ! INDEX_NUM = 274
DONE ! INDEX_NUM = 275
DONE ! INDEX_NUM = 276
DONE ! INDEX_NUM = 277
DONE ! INDEX_NUM = 278
DONE ! INDEX_NUM = 279
DONE ! INDEX_NUM = 280
DONE ! INDEX_NUM = 281
DONE ! INDEX_NUM = 282
DONE ! INDEX_NUM = 283
DONE ! INDEX_NUM = 284
DONE ! INDEX_NUM = 285
DONE ! INDEX_NUM = 286
DONE ! INDEX_NUM = 287
DONE ! INDEX_NUM = 288
DONE ! INDEX_NUM = 289
DONE ! INDEX_NUM = 290
DONE ! INDEX_NUM = 291
DONE ! INDEX_NUM = 292
DONE ! INDEX_NUM = 293
DONE ! INDEX_NUM = 294
DONE ! INDEX_NUM = 295
DONE ! INDEX_NUM = 296
DONE ! INDEX_NUM = 297
DONE ! INDEX_NUM = 298
DONE ! INDEX_NUM = 299
DONE ! INDEX_NUM = 300
DONE ! INDEX_NUM = 301
DONE ! INDEX_NUM = 302
DONE ! INDEX_NUM = 303
DONE ! INDEX_NUM = 304
DONE ! INDEX_NUM = 305
DONE ! INDEX_NUM = 306
DONE ! INDEX_NUM = 307
DONE ! INDEX_NUM = 308
DONE ! INDEX_NUM = 309
DONE ! INDEX_NUM = 310
DONE ! INDEX_NUM = 311
DONE ! INDEX_NUM = 312
DONE ! INDEX_NUM = 313
DONE ! INDEX_NUM = 314
DONE ! INDEX_NUM = 315
DONE ! INDEX_NUM = 316
DONE ! INDEX_NUM = 317
DONE ! INDEX_NUM = 318
DONE ! INDEX_NUM = 319
DONE ! INDEX_NUM = 320
DONE ! INDEX_NUM = 321
DONE ! INDEX_NUM = 322
DONE ! INDEX_NUM = 323
DONE ! INDEX_NUM = 324
DONE ! INDEX_NUM = 325
DONE ! INDEX_NUM = 326
DONE ! INDEX_NUM = 327
DONE ! INDEX_NUM = 328
DONE ! INDEX_NUM = 329
DONE ! INDEX_NUM = 330
DONE ! INDEX_NUM = 331
DONE ! INDEX_NUM = 332
DONE ! INDEX_NUM = 333
DONE ! INDEX_NUM = 334
DONE ! INDEX_NUM = 335
DONE ! INDEX_NUM = 336
DONE ! INDEX_NUM = 337
DONE ! INDEX_NUM = 338
DONE ! INDEX_NUM = 339
DONE ! INDEX_NUM = 340
DONE ! INDEX_NUM = 341
DONE ! INDEX_NUM = 342
DONE ! INDEX_NUM = 343
DONE ! INDEX_NUM = 344
DONE ! INDEX_NUM = 345
DONE ! INDEX_NUM = 346
DONE ! INDEX_NUM = 347
DONE ! INDEX_NUM = 348
DONE ! INDEX_NUM = 349
DONE ! INDEX_NUM = 350
DONE ! INDEX_NUM = 351
DONE ! INDEX_NUM = 352
DONE ! INDEX_NUM = 353
DONE ! INDEX_NUM = 354
DONE ! INDEX_NUM = 355
DONE ! INDEX_NUM = 356
DONE ! INDEX_NUM = 357
DONE ! INDEX_NUM = 358
DONE ! INDEX_NUM = 359
DONE ! INDEX_NUM = 360
DONE ! INDEX_NUM = 361
DONE ! INDEX_NUM = 362
DONE ! INDEX_NUM = 363
DONE ! INDEX_NUM = 364
DONE ! INDEX_NUM = 365
DONE ! INDEX_NUM = 366
DONE ! INDEX_NUM = 367
DONE ! INDEX_NUM = 368
DONE ! INDEX_NUM = 369
DONE ! INDEX_NUM = 370
DONE ! INDEX_NUM = 371
DONE ! INDEX_NUM = 372
DONE ! INDEX_NUM = 373
DONE ! INDEX_NUM = 374
DONE ! INDEX_NUM = 375
DONE ! INDEX_NUM = 376
DONE ! INDEX_NUM = 377
DONE ! INDEX_NUM = 378
DONE ! INDEX_NUM = 379
DONE ! INDEX_NUM = 380
DONE ! INDEX_NUM = 381
DONE ! INDEX_NUM = 382
DONE ! INDEX_NUM = 383
DONE ! INDEX_NUM = 384
DONE ! INDEX_NUM = 385
DONE ! INDEX_NUM = 386
DONE ! INDEX_NUM = 387
DONE ! INDEX_NUM = 388
DONE ! INDEX_NUM = 389
DONE ! INDEX_NUM = 390
DONE ! INDEX_NUM = 391
DONE ! INDEX_NUM = 392
DONE ! INDEX_NUM = 393
DONE ! INDEX_NUM = 394
DONE ! INDEX_NUM = 395
DONE ! INDEX_NUM = 396
DONE ! INDEX_NUM = 397
DONE ! INDEX_NUM = 398
DONE ! INDEX_NUM = 399
DONE ! INDEX_NUM = 400
DONE ! INDEX_NUM = 401
DONE ! INDEX_NUM = 402
DONE ! INDEX_NUM = 403
DONE ! INDEX_NUM = 404
DONE ! INDEX_NUM = 405
DONE ! INDEX_NUM = 406
DONE ! INDEX_NUM = 407
DONE ! INDEX_NUM = 408
DONE ! INDEX_NUM = 409
DONE ! INDEX_NUM = 410
DONE ! INDEX_NUM = 411
DONE ! INDEX_NUM = 412
DONE ! INDEX_NUM = 413
DONE ! INDEX_NUM = 414
DONE ! INDEX_NUM = 415
DONE ! INDEX_NUM = 416
DONE ! INDEX_NUM = 417
DONE ! INDEX_NUM = 418
DONE ! INDEX_NUM = 419
DONE ! INDEX_NUM = 420
DONE ! INDEX_NUM = 421
DONE ! INDEX_NUM = 422
DONE ! INDEX_NUM = 423
DONE ! INDEX_NUM = 424
DONE ! INDEX_NUM = 425
DONE ! INDEX_NUM = 426
DONE ! INDEX_NUM = 427
DONE ! INDEX_NUM = 428
DONE ! INDEX_NUM = 429
DONE ! INDEX_NUM = 430
DONE ! INDEX_NUM = 431
DONE ! INDEX_NUM = 432
DONE ! INDEX_NUM = 433
DONE ! INDEX_NUM = 434
DONE ! INDEX_NUM = 435
DONE ! INDEX_NUM = 436
DONE ! INDEX_NUM = 437
DONE ! INDEX_NUM = 438
DONE ! INDEX_NUM = 439
DONE ! INDEX_NUM = 440
DONE ! INDEX_NUM = 441
DONE ! INDEX_NUM = 442
DONE ! INDEX_NUM = 443
DONE ! INDEX_NUM = 444
DONE ! INDEX_NUM = 445
DONE ! INDEX_NUM = 446
DONE ! INDEX_NUM = 447
DONE ! INDEX_NUM = 448
DONE ! INDEX_NUM = 449
DONE ! INDEX_NUM = 450
DONE ! INDEX_NUM = 451
DONE ! INDEX_NUM = 452
DONE ! INDEX_NUM = 453
DONE ! INDEX_NUM = 454
DONE ! INDEX_NUM = 455
DONE ! INDEX_NUM = 456
DONE ! INDEX_NUM = 457
DONE ! INDEX_NUM = 458
DONE ! INDEX_NUM = 459
DONE ! INDEX_NUM = 460
DONE ! INDEX_NUM = 461
DONE ! INDEX_NUM = 462
DONE ! INDEX_NUM = 463
DONE ! INDEX_NUM = 464
DONE ! INDEX_NUM = 465
DONE ! INDEX_NUM = 466
DONE ! INDEX_NUM = 467
DONE ! INDEX_NUM = 468
DONE ! INDEX_NUM = 469
DONE ! INDEX_NUM = 470
DONE ! INDEX_NUM = 471
DONE ! INDEX_NUM = 472
DONE ! INDEX_NUM = 473
DONE ! INDEX_NUM = 474
DONE ! INDEX_NUM = 475
DONE ! INDEX_NUM = 476
DONE ! INDEX_NUM = 477
DONE ! INDEX_NUM = 478
DONE ! INDEX_NUM = 479
DONE ! INDEX_NUM = 480
DONE ! INDEX_NUM = 481
DONE ! INDEX_NUM = 482
DONE ! INDEX_NUM = 483
DONE ! INDEX_NUM = 484
DONE ! INDEX_NUM = 485
DONE ! INDEX_NUM = 486
DONE ! INDEX_NUM = 487
DONE ! INDEX_NUM = 488
DONE ! INDEX_NUM = 489
DONE ! INDEX_NUM = 490
DONE ! INDEX_NUM = 491
DONE ! INDEX_NUM = 492
DONE ! INDEX_NUM = 493
DONE ! INDEX_NUM = 494
DONE ! INDEX_NUM = 495
DONE ! INDEX_NUM = 496
DONE ! INDEX_NUM = 497
DONE ! INDEX_NUM = 498
DONE ! INDEX_NUM = 499
DONE ! INDEX_NUM = 500
DONE ! INDEX_NUM = 501
DONE ! INDEX_NUM = 502
DONE ! INDEX_NUM = 503
DONE ! INDEX_NUM = 504
DONE ! INDEX_NUM = 505
DONE ! INDEX_NUM = 506
DONE ! INDEX_NUM = 507
DONE ! INDEX_NUM = 508
DONE ! INDEX_NUM = 509
DONE ! INDEX_NUM = 510
DONE ! INDEX_NUM = 511
DONE ! INDEX_NUM = 512
DONE ! INDEX_NUM = 513
DONE ! INDEX_NUM = 514
DONE ! INDEX_NUM = 515
DONE ! INDEX_NUM = 516
DONE ! INDEX_NUM = 517
DONE ! INDEX_NUM = 518
DONE ! INDEX_NUM = 519
DONE ! INDEX_NUM = 520
DONE ! INDEX_NUM = 521
DONE ! INDEX_NUM = 522
DONE ! INDEX_NUM = 523
DONE ! INDEX_NUM = 524
DONE ! INDEX_NUM = 525
DONE ! INDEX_NUM = 526
DONE ! INDEX_NUM = 527
DONE ! INDEX_NUM = 528
DONE ! INDEX_NUM = 529
DONE ! INDEX_NUM = 530
DONE ! INDEX_NUM = 531
DONE ! INDEX_NUM = 532
DONE ! INDEX_NUM = 533
DONE ! INDEX_NUM = 534
DONE ! INDEX_NUM = 535
DONE ! INDEX_NUM = 536
DONE ! INDEX_NUM = 537
DONE ! INDEX_NUM = 538
DONE ! INDEX_NUM = 539
DONE ! INDEX_NUM = 540
DONE ! INDEX_NUM = 541
DONE ! INDEX_NUM = 542
DONE ! INDEX_NUM = 543
DONE ! INDEX_NUM = 544
DONE ! INDEX_NUM = 545
DONE ! INDEX_NUM = 546
DONE ! INDEX_NUM = 547
DONE ! INDEX_NUM = 548
DONE ! INDEX_NUM = 549
DONE ! INDEX_NUM = 550
DONE ! INDEX_NUM = 551
DONE ! INDEX_NUM = 552
DONE ! INDEX_NUM = 553
DONE ! INDEX_NUM = 554
DONE ! INDEX_NUM = 555
DONE ! INDEX_NUM = 556
DONE ! INDEX_NUM = 557
DONE ! INDEX_NUM = 558
DONE ! INDEX_NUM = 559
DONE ! INDEX_NUM = 560
DONE ! INDEX_NUM = 561
DONE ! INDEX_NUM = 562
DONE ! INDEX_NUM = 563
DONE ! INDEX_NUM = 564
DONE ! INDEX_NUM = 565
DONE ! INDEX_NUM = 566
DONE ! INDEX_NUM = 567
DONE ! INDEX_NUM = 568
DONE ! INDEX_NUM = 569
DONE ! INDEX_NUM = 570
DONE ! INDEX_NUM = 571
DONE ! INDEX_NUM = 572
DONE ! INDEX_NUM = 573
DONE ! INDEX_NUM = 574
DONE ! INDEX_NUM = 575
DONE ! INDEX_NUM = 576
DONE ! INDEX_NUM = 577
DONE ! INDEX_NUM = 578
DONE ! INDEX_NUM = 579
DONE ! INDEX_NUM = 580
DONE ! INDEX_NUM = 581
DONE ! INDEX_NUM = 582
DONE ! INDEX_NUM = 583
DONE ! INDEX_NUM = 584
DONE ! INDEX_NUM = 585
DONE ! INDEX_NUM = 586
DONE ! INDEX_NUM = 587
DONE ! INDEX_NUM = 588
DONE ! INDEX_NUM = 589
DONE ! INDEX_NUM = 590
DONE ! INDEX_NUM = 591
DONE ! INDEX_NUM = 592
DONE ! INDEX_NUM = 593
DONE ! INDEX_NUM = 594
DONE ! INDEX_NUM = 595
DONE ! INDEX_NUM = 596
DONE ! INDEX_NUM = 597
DONE ! INDEX_NUM = 598
DONE ! INDEX_NUM = 599
DONE ! INDEX_NUM = 600
DONE ! INDEX_NUM = 601
DONE ! INDEX_NUM = 602
DONE ! INDEX_NUM = 603
DONE ! INDEX_NUM = 604
DONE ! INDEX_NUM = 605
DONE ! INDEX_NUM = 606
DONE ! INDEX_NUM = 607
DONE ! INDEX_NUM = 608
DONE ! INDEX_NUM = 609
DONE ! INDEX_NUM = 610
DONE ! INDEX_NUM = 611
DONE ! INDEX_NUM = 612
DONE ! INDEX_NUM = 613
DONE ! INDEX_NUM = 614
DONE ! INDEX_NUM = 615
DONE ! INDEX_NUM = 616
DONE ! INDEX_NUM = 617
DONE ! INDEX_NUM = 618
DONE ! INDEX_NUM = 619
DONE ! INDEX_NUM = 620
DONE ! INDEX_NUM = 621
DONE ! INDEX_NUM = 622
DONE ! INDEX_NUM = 623
DONE ! INDEX_NUM = 624
DONE ! INDEX_NUM = 625
DONE ! INDEX_NUM = 626
DONE ! INDEX_NUM = 627
DONE ! INDEX_NUM = 628
DONE ! INDEX_NUM = 629
DONE ! INDEX_NUM = 630
DONE ! INDEX_NUM = 631
DONE ! INDEX_NUM = 632
DONE ! INDEX_NUM = 633
DONE ! INDEX_NUM = 634
DONE ! INDEX_NUM = 635
DONE ! INDEX_NUM = 636
DONE ! INDEX_NUM = 637
DONE ! INDEX_NUM = 638
DONE ! INDEX_NUM = 639
DONE ! INDEX_NUM = 640
DONE ! INDEX_NUM = 641
DONE ! INDEX_NUM = 642
DONE ! INDEX_NUM = 643
DONE ! INDEX_NUM = 644
DONE ! INDEX_NUM = 645
DONE ! INDEX_NUM = 646
DONE ! INDEX_NUM = 647
DONE ! INDEX_NUM = 648
DONE ! INDEX_NUM = 649
DONE ! INDEX_NUM = 650
DONE ! INDEX_NUM = 651
DONE ! INDEX_NUM = 652
DONE ! INDEX_NUM = 653
DONE ! INDEX_NUM = 654
DONE ! INDEX_NUM = 655
DONE ! INDEX_NUM = 656
DONE ! INDEX_NUM = 657
DONE ! INDEX_NUM = 658
DONE ! INDEX_NUM = 659
DONE ! INDEX_NUM = 660
DONE ! INDEX_NUM = 661
DONE ! INDEX_NUM = 662
DONE ! INDEX_NUM = 663
DONE ! INDEX_NUM = 664
DONE ! INDEX_NUM = 665
DONE ! INDEX_NUM = 666
DONE ! INDEX_NUM = 667
DONE ! INDEX_NUM = 668
DONE ! INDEX_NUM = 669
DONE ! INDEX_NUM = 670
DONE ! INDEX_NUM = 671
DONE ! INDEX_NUM = 672
DONE ! INDEX_NUM = 673
DONE ! INDEX_NUM = 674
DONE ! INDEX_NUM = 675
DONE ! INDEX_NUM = 676
DONE ! INDEX_NUM = 677
DONE ! INDEX_NUM = 678
DONE ! INDEX_NUM = 679
DONE ! INDEX_NUM = 680
DONE ! INDEX_NUM = 681
DONE ! INDEX_NUM = 682
DONE ! INDEX_NUM = 683
DONE ! INDEX_NUM = 684
DONE ! INDEX_NUM = 685
DONE ! INDEX_NUM = 686
DONE ! INDEX_NUM = 687
DONE ! INDEX_NUM = 688
DONE ! INDEX_NUM = 689
DONE ! INDEX_NUM = 690
DONE ! INDEX_NUM = 691
DONE ! INDEX_NUM = 692
DONE ! INDEX_NUM = 693
DONE ! INDEX_NUM = 694
DONE ! INDEX_NUM = 695
DONE ! INDEX_NUM = 696
DONE ! INDEX_NUM = 697
DONE ! INDEX_NUM = 698
DONE ! INDEX_NUM = 699
DONE ! INDEX_NUM = 700
DONE ! INDEX_NUM = 701
DONE ! INDEX_NUM = 702
DONE ! INDEX_NUM = 703
DONE ! INDEX_NUM = 704
DONE ! INDEX_NUM = 705
DONE ! INDEX_NUM = 706
DONE ! INDEX_NUM = 707
DONE ! INDEX_NUM = 708
DONE ! INDEX_NUM = 709
DONE ! INDEX_NUM = 710
DONE ! INDEX_NUM = 711
DONE ! INDEX_NUM = 712
DONE ! INDEX_NUM = 713
DONE ! INDEX_NUM = 714
DONE ! INDEX_NUM = 715
DONE ! INDEX_NUM = 716
DONE ! INDEX_NUM = 717
DONE ! INDEX_NUM = 718
DONE ! INDEX_NUM = 719
DONE ! INDEX_NUM = 720
DONE ! INDEX_NUM = 721
DONE ! INDEX_NUM = 722
DONE ! INDEX_NUM = 723
DONE ! INDEX_NUM = 724
DONE ! INDEX_NUM = 725
DONE ! INDEX_NUM = 726
DONE ! INDEX_NUM = 727
DONE ! INDEX_NUM = 728
DONE ! INDEX_NUM = 729
DONE ! INDEX_NUM = 730
DONE ! INDEX_NUM = 731
DONE ! INDEX_NUM = 732
DONE ! INDEX_NUM = 733
DONE ! INDEX_NUM = 734
DONE ! INDEX_NUM = 735
DONE ! INDEX_NUM = 736
DONE ! INDEX_NUM = 737
DONE ! INDEX_NUM = 738
DONE ! INDEX_NUM = 739
DONE ! INDEX_NUM = 740
DONE ! INDEX_NUM = 741
DONE ! INDEX_NUM = 742
DONE ! INDEX_NUM = 743
DONE ! INDEX_NUM = 744
DONE ! INDEX_NUM = 745
DONE ! INDEX_NUM = 746
DONE ! INDEX_NUM = 747
DONE ! INDEX_NUM = 748
DONE ! INDEX_NUM = 749
DONE ! INDEX_NUM = 750
DONE ! INDEX_NUM = 751
DONE ! INDEX_NUM = 752
DONE ! INDEX_NUM = 753
DONE ! INDEX_NUM = 754
DONE ! INDEX_NUM = 755
DONE ! INDEX_NUM = 756
DONE ! INDEX_NUM = 757
DONE ! INDEX_NUM = 758
DONE ! INDEX_NUM = 759
DONE ! INDEX_NUM = 760
DONE ! INDEX_NUM = 761
DONE ! INDEX_NUM = 762
DONE ! INDEX_NUM = 763
DONE ! INDEX_NUM = 764
DONE ! INDEX_NUM = 765
DONE ! INDEX_NUM = 766
DONE ! INDEX_NUM = 767
DONE ! INDEX_NUM = 768
DONE ! INDEX_NUM = 769
DONE ! INDEX_NUM = 770
DONE ! INDEX_NUM = 771
DONE ! INDEX_NUM = 772
DONE ! INDEX_NUM = 773
DONE ! INDEX_NUM = 774
DONE ! INDEX_NUM = 775
DONE ! INDEX_NUM = 776
DONE ! INDEX_NUM = 777
DONE ! INDEX_NUM = 778
DONE ! INDEX_NUM = 779
DONE ! INDEX_NUM = 780
DONE ! INDEX_NUM = 781
DONE ! INDEX_NUM = 782
DONE ! INDEX_NUM = 783
DONE ! INDEX_NUM = 784
DONE ! INDEX_NUM = 785
DONE ! INDEX_NUM = 786
DONE ! INDEX_NUM = 787
DONE ! INDEX_NUM = 788
DONE ! INDEX_NUM = 789
DONE ! INDEX_NUM = 790
DONE ! INDEX_NUM = 791
DONE ! INDEX_NUM = 792
DONE ! INDEX_NUM = 793
DONE ! INDEX_NUM = 794
DONE ! INDEX_NUM = 795
DONE ! INDEX_NUM = 796
DONE ! INDEX_NUM = 797
DONE ! INDEX_NUM = 798
DONE ! INDEX_NUM = 799
DONE ! INDEX_NUM = 800
DONE ! INDEX_NUM = 801
DONE ! INDEX_NUM = 802
DONE ! INDEX_NUM = 803
DONE ! INDEX_NUM = 804
DONE ! INDEX_NUM = 805
DONE ! INDEX_NUM = 806
DONE ! INDEX_NUM = 807
DONE ! INDEX_NUM = 808
DONE ! INDEX_NUM = 809
DONE ! INDEX_NUM = 810
DONE ! INDEX_NUM = 811
DONE ! INDEX_NUM = 812
DONE ! INDEX_NUM = 813
DONE ! INDEX_NUM = 814
DONE ! INDEX_NUM = 815
DONE ! INDEX_NUM = 816
DONE ! INDEX_NUM = 817
DONE ! INDEX_NUM = 818
DONE ! INDEX_NUM = 819
DONE ! INDEX_NUM = 820
DONE ! INDEX_NUM = 821
DONE ! INDEX_NUM = 822
DONE ! INDEX_NUM = 823
DONE ! INDEX_NUM = 824
DONE ! INDEX_NUM = 825
DONE ! INDEX_NUM = 826
DONE ! INDEX_NUM = 827
DONE ! INDEX_NUM = 828
DONE ! INDEX_NUM = 829
DONE ! INDEX_NUM = 830
DONE ! INDEX_NUM = 831
DONE ! INDEX_NUM = 832
DONE ! INDEX_NUM = 833
DONE ! INDEX_NUM = 834
DONE ! INDEX_NUM = 835
DONE ! INDEX_NUM = 836
DONE ! INDEX_NUM = 837
DONE ! INDEX_NUM = 838
DONE ! INDEX_NUM = 839
DONE ! INDEX_NUM = 840
DONE ! INDEX_NUM = 841
DONE ! INDEX_NUM = 842
DONE ! INDEX_NUM = 843
DONE ! INDEX_NUM = 844
DONE ! INDEX_NUM = 845
DONE ! INDEX_NUM = 846
DONE ! INDEX_NUM = 847
DONE ! INDEX_NUM = 848
DONE ! INDEX_NUM = 849
DONE ! INDEX_NUM = 850
DONE ! INDEX_NUM = 851
DONE ! INDEX_NUM = 852
DONE ! INDEX_NUM = 853
DONE ! INDEX_NUM = 854
DONE ! INDEX_NUM = 855
DONE ! INDEX_NUM = 856
DONE ! INDEX_NUM = 857
DONE ! INDEX_NUM = 858
DONE ! INDEX_NUM = 859
DONE ! INDEX_NUM = 860
DONE ! INDEX_NUM = 861
DONE ! INDEX_NUM = 862
DONE ! INDEX_NUM = 863
DONE ! INDEX_NUM = 864
DONE ! INDEX_NUM = 865
DONE ! INDEX_NUM = 866
DONE ! INDEX_NUM = 867
DONE ! INDEX_NUM = 868
DONE ! INDEX_NUM = 869
DONE ! INDEX_NUM = 870
DONE ! INDEX_NUM = 871
DONE ! INDEX_NUM = 872
DONE ! INDEX_NUM = 873

In [6]:
#(2) 처리 결과 확인하기.
RANDOM_POINT

,rand_point,자치구,행정동_코드,행정동,세대_COUNT,노래연습장_COUNT,당구장_COUNT,PC방_COUNT,금연구역_10m_COUNT,금연구역_50m_COUNT,음식점_외식_COUNT,음식점_회식_COUNT,음식점_카페_COUNT,위도,경도,geometry,SCORE_b
0,0,금천구,1154568000,시흥제2동,0.250891,1,0,0,2,1,9,3,1,37.449962,126.913406,POINT (192337.7432523154 438954.0766042818),2499.000000
1,1,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,11,4,1,37.449964,126.914394,POINT (192425.2336731556 438954.2123132667),2981.000000
2,2,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,11,4,1,37.449939,126.914258,POINT (192413.1979568179 438951.4329210447),2981.000000
3,3,금천구,1154568000,시흥제2동,0.250891,2,0,0,2,1,9,4,1,37.449956,126.913289,POINT (192327.4056526743 438953.4538745985),2535.000000
4,4,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,12,4,1,37.450008,126.913638,POINT (192358.2717906134 438959.210054699),3246.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40286,41191,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.499947,126.953611,POINT (195897.9891959261 444499.2420208962),246.316215
40287,41192,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.500272,126.953683,POINT (195904.4341447904 444535.2696354929),246.316215
40288,41193,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.500105,126.953733,POINT (195908.8060317755 444516.8050831873),246.316215
40289,41194,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,1,0,0,37.500540,126.953708,POINT (195906.6493213855 444565.0878704682),510.596215
40290,41195,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.499826,126.953583,POINT (195895.5612148321 444485.8452144368),246.316215

In [11]:
#02. SCORE_s 계산하기. 
#(1) 처리하기. 
RANDOM_POINT['SCORE_s'] = 0

for i in range(len(RANDOM_POINT))                                           :
    for k in range(len(SHAP_VAL))                                           :
        if RANDOM_POINT['행정동_코드'][i] == SHAP_VAL['행정동_코드'][k] :    
            세대_val         = RANDOM_POINT['세대_COUNT'][i] * SHAP_VAL['세대'][k]
            노래연습장_val   = RANDOM_POINT['노래연습장_COUNT'][i] * SHAP_VAL['노래연습장'][k]
            당구장_val       = RANDOM_POINT['당구장_COUNT'][i] * SHAP_VAL['당구장'][k]
            PC방_val         = RANDOM_POINT['PC방_COUNT'][i] * SHAP_VAL['PC방'][k]
            금연구역_10m_val = RANDOM_POINT['금연구역_10m_COUNT'][i] * SHAP_VAL['금연구역_10m'][k]
            금연구역_50m_val = RANDOM_POINT['금연구역_50m_COUNT'][i] * SHAP_VAL['금연구역_50m'][k]
            음식점_외식_val  = RANDOM_POINT['음식점_외식_COUNT'][i] * SHAP_VAL['음식점_외식'][k]
            음식점_회식_val  = RANDOM_POINT['음식점_회식_COUNT'][i] * SHAP_VAL['음식점_회식'][k]
            음식점_카페_val  = RANDOM_POINT['음식점_카페_COUNT'][i] * SHAP_VAL['음식점_카페'][k]
            SHAP_SUM         = 세대_val + 노래연습장_val + 당구장_val + PC방_val + 금연구역_10m_val + 금연구역_50m_val + 음식점_외식_val + 음식점_회식_val + 음식점_카페_val

    RANDOM_POINT['SCORE_s'][i] = SHAP_SUM
    print(f'DONE ! INDEX_NUM = {i}')

DONE ! INDEX_NUM = 0
DONE ! INDEX_NUM = 1
DONE ! INDEX_NUM = 2
DONE ! INDEX_NUM = 3
DONE ! INDEX_NUM = 4
DONE ! INDEX_NUM = 5
DONE ! INDEX_NUM = 6
DONE ! INDEX_NUM = 7
DONE ! INDEX_NUM = 8
DONE ! INDEX_NUM = 9
DONE ! INDEX_NUM = 10
DONE ! INDEX_NUM = 11
DONE ! INDEX_NUM = 12
DONE ! INDEX_NUM = 13
DONE ! INDEX_NUM = 14
DONE ! INDEX_NUM = 15
DONE ! INDEX_NUM = 16
DONE ! INDEX_NUM = 17
DONE ! INDEX_NUM = 18
DONE ! INDEX_NUM = 19
DONE ! INDEX_NUM = 20
DONE ! INDEX_NUM = 21
DONE ! INDEX_NUM = 22
DONE ! INDEX_NUM = 23
DONE ! INDEX_NUM = 24
DONE ! INDEX_NUM = 25
DONE ! INDEX_NUM = 26
DONE ! INDEX_NUM = 27
DONE ! INDEX_NUM = 28
DONE ! INDEX_NUM = 29
DONE ! INDEX_NUM = 30
DONE ! INDEX_NUM = 31
DONE ! INDEX_NUM = 32
DONE ! INDEX_NUM = 33
DONE ! INDEX_NUM = 34
DONE ! INDEX_NUM = 35
DONE ! INDEX_NUM = 36
DONE ! INDEX_NUM = 37
DONE ! INDEX_NUM = 38
DONE ! INDEX_NUM = 39
DONE ! INDEX_NUM = 40
DONE ! INDEX_NUM = 41
DONE ! INDEX_NUM = 42
DONE ! INDEX_NUM = 43
DONE ! INDEX_NUM = 44
DONE ! INDEX_NUM = 45
DONE ! INDEX_NUM = 46
DONE ! INDEX_NUM = 47
DONE ! INDEX_NUM = 48
DONE ! INDEX_NUM = 49
DONE ! INDEX_NUM = 50
DONE ! INDEX_NUM = 51
DONE ! INDEX_NUM = 52
DONE ! INDEX_NUM = 53
DONE ! INDEX_NUM = 54
DONE ! INDEX_NUM = 55
DONE ! INDEX_NUM = 56
DONE ! INDEX_NUM = 57
DONE ! INDEX_NUM = 58
DONE ! INDEX_NUM = 59
DONE ! INDEX_NUM = 60
DONE ! INDEX_NUM = 61
DONE ! INDEX_NUM = 62
DONE ! INDEX_NUM = 63
DONE ! INDEX_NUM = 64
DONE ! INDEX_NUM = 65
DONE ! INDEX_NUM = 66
DONE ! INDEX_NUM = 67
DONE ! INDEX_NUM = 68
DONE ! INDEX_NUM = 69
DONE ! INDEX_NUM = 70
DONE ! INDEX_NUM = 71
DONE ! INDEX_NUM = 72
DONE ! INDEX_NUM = 73
DONE ! INDEX_NUM = 74
DONE ! INDEX_NUM = 75
DONE ! INDEX_NUM = 76
DONE ! INDEX_NUM = 77
DONE ! INDEX_NUM = 78
DONE ! INDEX_NUM = 79
DONE ! INDEX_NUM = 80
DONE ! INDEX_NUM = 81
DONE ! INDEX_NUM = 82
DONE ! INDEX_NUM = 83
DONE ! INDEX_NUM = 84
DONE ! INDEX_NUM = 85
DONE ! INDEX_NUM = 86
DONE ! INDEX_NUM = 87
DONE ! INDEX_NUM = 88
DONE ! INDEX_NUM = 89
DONE ! INDEX_NUM = 90
DONE ! INDEX_NUM = 91
DONE ! INDEX_NUM = 92
DONE ! INDEX_NUM = 93
DONE ! INDEX_NUM = 94
DONE ! INDEX_NUM = 95
DONE ! INDEX_NUM = 96
DONE ! INDEX_NUM = 97
DONE ! INDEX_NUM = 98
DONE ! INDEX_NUM = 99
DONE ! INDEX_NUM = 100
DONE ! INDEX_NUM = 101
DONE ! INDEX_NUM = 102
DONE ! INDEX_NUM = 103
DONE ! INDEX_NUM = 104
DONE ! INDEX_NUM = 105
DONE ! INDEX_NUM = 106
DONE ! INDEX_NUM = 107
DONE ! INDEX_NUM = 108
DONE ! INDEX_NUM = 109
DONE ! INDEX_NUM = 110
DONE ! INDEX_NUM = 111
DONE ! INDEX_NUM = 112
DONE ! INDEX_NUM = 113
DONE ! INDEX_NUM = 114
DONE ! INDEX_NUM = 115
DONE ! INDEX_NUM = 116
DONE ! INDEX_NUM = 117
DONE ! INDEX_NUM = 118
DONE ! INDEX_NUM = 119
DONE ! INDEX_NUM = 120
DONE ! INDEX_NUM = 121
DONE ! INDEX_NUM = 122
DONE ! INDEX_NUM = 123
DONE ! INDEX_NUM = 124
DONE ! INDEX_NUM = 125
DONE ! INDEX_NUM = 126
DONE ! INDEX_NUM = 127
DONE ! INDEX_NUM = 128
DONE ! INDEX_NUM = 129
DONE ! INDEX_NUM = 130
DONE ! INDEX_NUM = 131
DONE ! INDEX_NUM = 132
DONE ! INDEX_NUM = 133
DONE ! INDEX_NUM = 134
DONE ! INDEX_NUM = 135
DONE ! INDEX_NUM = 136
DONE ! INDEX_NUM = 137
DONE ! INDEX_NUM = 138
DONE ! INDEX_NUM = 139
DONE ! INDEX_NUM = 140
DONE ! INDEX_NUM = 141
DONE ! INDEX_NUM = 142
DONE ! INDEX_NUM = 143
DONE ! INDEX_NUM = 144
DONE ! INDEX_NUM = 145
DONE ! INDEX_NUM = 146
DONE ! INDEX_NUM = 147
DONE ! INDEX_NUM = 148
DONE ! INDEX_NUM = 149
DONE ! INDEX_NUM = 150
DONE ! INDEX_NUM = 151
DONE ! INDEX_NUM = 152
DONE ! INDEX_NUM = 153
DONE ! INDEX_NUM = 154
DONE ! INDEX_NUM = 155
DONE ! INDEX_NUM = 156
DONE ! INDEX_NUM = 157
DONE ! INDEX_NUM = 158
DONE ! INDEX_NUM = 159
DONE ! INDEX_NUM = 160
DONE ! INDEX_NUM = 161
DONE ! INDEX_NUM = 162
DONE ! INDEX_NUM = 163
DONE ! INDEX_NUM = 164
DONE ! INDEX_NUM = 165
DONE ! INDEX_NUM = 166
DONE ! INDEX_NUM = 167
DONE ! INDEX_NUM = 168
DONE ! INDEX_NUM = 169
DONE ! INDEX_NUM = 170
DONE ! INDEX_NUM = 171
DONE ! INDEX_NUM = 172
DONE ! INDEX_NUM = 173
DONE ! INDEX_NUM = 174
DONE ! INDEX_NUM = 175
DONE ! INDEX_NUM = 176
DONE ! INDEX_NUM = 177
DONE ! INDEX_NUM = 178
DONE ! INDEX_NUM = 179
DONE ! INDEX_NUM = 180
DONE ! INDEX_NUM = 181
DONE ! INDEX_NUM = 182
DONE ! INDEX_NUM = 183
DONE ! INDEX_NUM = 184
DONE ! INDEX_NUM = 185
DONE ! INDEX_NUM = 186
DONE ! INDEX_NUM = 187
DONE ! INDEX_NUM = 188
DONE ! INDEX_NUM = 189
DONE ! INDEX_NUM = 190
DONE ! INDEX_NUM = 191
DONE ! INDEX_NUM = 192
DONE ! INDEX_NUM = 193
DONE ! INDEX_NUM = 194
DONE ! INDEX_NUM = 195
DONE ! INDEX_NUM = 196
DONE ! INDEX_NUM = 197
DONE ! INDEX_NUM = 198
DONE ! INDEX_NUM = 199
DONE ! INDEX_NUM = 200
DONE ! INDEX_NUM = 201
DONE ! INDEX_NUM = 202
DONE ! INDEX_NUM = 203
DONE ! INDEX_NUM = 204
DONE ! INDEX_NUM = 205
DONE ! INDEX_NUM = 206
DONE ! INDEX_NUM = 207
DONE ! INDEX_NUM = 208
DONE ! INDEX_NUM = 209
DONE ! INDEX_NUM = 210
DONE ! INDEX_NUM = 211
DONE ! INDEX_NUM = 212
DONE ! INDEX_NUM = 213
DONE ! INDEX_NUM = 214
DONE ! INDEX_NUM = 215
DONE ! INDEX_NUM = 216
DONE ! INDEX_NUM = 217
DONE ! INDEX_NUM = 218
DONE ! INDEX_NUM = 219
DONE ! INDEX_NUM = 220
DONE ! INDEX_NUM = 221
DONE ! INDEX_NUM = 222
DONE ! INDEX_NUM = 223
DONE ! INDEX_NUM = 224
DONE ! INDEX_NUM = 225
DONE ! INDEX_NUM = 226
DONE ! INDEX_NUM = 227
DONE ! INDEX_NUM = 228
DONE ! INDEX_NUM = 229
DONE ! INDEX_NUM = 230
DONE ! INDEX_NUM = 231
DONE ! INDEX_NUM = 232
DONE ! INDEX_NUM = 233
DONE ! INDEX_NUM = 234
DONE ! INDEX_NUM = 235
DONE ! INDEX_NUM = 236
DONE ! INDEX_NUM = 237
DONE ! INDEX_NUM = 238
DONE ! INDEX_NUM = 239
DONE ! INDEX_NUM = 240
DONE ! INDEX_NUM = 241
DONE ! INDEX_NUM = 242
DONE ! INDEX_NUM = 243
DONE ! INDEX_NUM = 244
DONE ! INDEX_NUM = 245
DONE ! INDEX_NUM = 246
DONE ! INDEX_NUM = 247
DONE ! INDEX_NUM = 248
DONE ! INDEX_NUM = 249
DONE ! INDEX_NUM = 250
DONE ! INDEX_NUM = 251
DONE ! INDEX_NUM = 252
DONE ! INDEX_NUM = 253
DONE ! INDEX_NUM = 254
DONE ! INDEX_NUM = 255
DONE ! INDEX_NUM = 256
DONE ! INDEX_NUM = 257
DONE ! INDEX_NUM = 258
DONE ! INDEX_NUM = 259
DONE ! INDEX_NUM = 260
DONE ! INDEX_NUM = 261
DONE ! INDEX_NUM = 262
DONE ! INDEX_NUM = 263
DONE ! INDEX_NUM = 264
DONE ! INDEX_NUM = 265
DONE ! INDEX_NUM = 266
DONE ! INDEX_NUM = 267
DONE ! INDEX_NUM = 268
DONE ! INDEX_NUM = 269
DONE ! INDEX_NUM = 270
DONE ! INDEX_NUM = 271
DONE ! INDEX_NUM = 272
DONE ! INDEX_NUM = 273
DONE ! INDEX_NUM = 274
DONE ! INDEX_NUM = 275
DONE ! INDEX_NUM = 276
DONE ! INDEX_NUM = 277
DONE ! INDEX_NUM = 278
DONE ! INDEX_NUM = 279
DONE ! INDEX_NUM = 280
DONE ! INDEX_NUM = 281
DONE ! INDEX_NUM = 282
DONE ! INDEX_NUM = 283
DONE ! INDEX_NUM = 284
DONE ! INDEX_NUM = 285
DONE ! INDEX_NUM = 286
DONE ! INDEX_NUM = 287
DONE ! INDEX_NUM = 288
DONE ! INDEX_NUM = 289
DONE ! INDEX_NUM = 290
DONE ! INDEX_NUM = 291
DONE ! INDEX_NUM = 292
DONE ! INDEX_NUM = 293
DONE ! INDEX_NUM = 294
DONE ! INDEX_NUM = 295
DONE ! INDEX_NUM = 296
DONE ! INDEX_NUM = 297
DONE ! INDEX_NUM = 298
DONE ! INDEX_NUM = 299
DONE ! INDEX_NUM = 300
DONE ! INDEX_NUM = 301
DONE ! INDEX_NUM = 302
DONE ! INDEX_NUM = 303
DONE ! INDEX_NUM = 304
DONE ! INDEX_NUM = 305
DONE ! INDEX_NUM = 306
DONE ! INDEX_NUM = 307
DONE ! INDEX_NUM = 308
DONE ! INDEX_NUM = 309
DONE ! INDEX_NUM = 310
DONE ! INDEX_NUM = 311
DONE ! INDEX_NUM = 312
DONE ! INDEX_NUM = 313
DONE ! INDEX_NUM = 314
DONE ! INDEX_NUM = 315
DONE ! INDEX_NUM = 316
DONE ! INDEX_NUM = 317
DONE ! INDEX_NUM = 318
DONE ! INDEX_NUM = 319
DONE ! INDEX_NUM = 320
DONE ! INDEX_NUM = 321
DONE ! INDEX_NUM = 322
DONE ! INDEX_NUM = 323
DONE ! INDEX_NUM = 324
DONE ! INDEX_NUM = 325
DONE ! INDEX_NUM = 326
DONE ! INDEX_NUM = 327
DONE ! INDEX_NUM = 328
DONE ! INDEX_NUM = 329
DONE ! INDEX_NUM = 330
DONE ! INDEX_NUM = 331
DONE ! INDEX_NUM = 332
DONE ! INDEX_NUM = 333
DONE ! INDEX_NUM = 334
DONE ! INDEX_NUM = 335
DONE ! INDEX_NUM = 336
DONE ! INDEX_NUM = 337
DONE ! INDEX_NUM = 338
DONE ! INDEX_NUM = 339
DONE ! INDEX_NUM = 340
DONE ! INDEX_NUM = 341
DONE ! INDEX_NUM = 342
DONE ! INDEX_NUM = 343
DONE ! INDEX_NUM = 344
DONE ! INDEX_NUM = 345
DONE ! INDEX_NUM = 346
DONE ! INDEX_NUM = 347
DONE ! INDEX_NUM = 348
DONE ! INDEX_NUM = 349
DONE ! INDEX_NUM = 350
DONE ! INDEX_NUM = 351
DONE ! INDEX_NUM = 352
DONE ! INDEX_NUM = 353
DONE ! INDEX_NUM = 354
DONE ! INDEX_NUM = 355
DONE ! INDEX_NUM = 356
DONE ! INDEX_NUM = 357
DONE ! INDEX_NUM = 358
DONE ! INDEX_NUM = 359
DONE ! INDEX_NUM = 360
DONE ! INDEX_NUM = 361
DONE ! INDEX_NUM = 362
DONE ! INDEX_NUM = 363
DONE ! INDEX_NUM = 364
DONE ! INDEX_NUM = 365
DONE ! INDEX_NUM = 366
DONE ! INDEX_NUM = 367
DONE ! INDEX_NUM = 368
DONE ! INDEX_NUM = 369
DONE ! INDEX_NUM = 370
DONE ! INDEX_NUM = 371
DONE ! INDEX_NUM = 372
DONE ! INDEX_NUM = 373
DONE ! INDEX_NUM = 374
DONE ! INDEX_NUM = 375
DONE ! INDEX_NUM = 376
DONE ! INDEX_NUM = 377
DONE ! INDEX_NUM = 378
DONE ! INDEX_NUM = 379
DONE ! INDEX_NUM = 380
DONE ! INDEX_NUM = 381
DONE ! INDEX_NUM = 382
DONE ! INDEX_NUM = 383
DONE ! INDEX_NUM = 384
DONE ! INDEX_NUM = 385
DONE ! INDEX_NUM = 386
DONE ! INDEX_NUM = 387
DONE ! INDEX_NUM = 388
DONE ! INDEX_NUM = 389
DONE ! INDEX_NUM = 390
DONE ! INDEX_NUM = 391
DONE ! INDEX_NUM = 392
DONE ! INDEX_NUM = 393
DONE ! INDEX_NUM = 394
DONE ! INDEX_NUM = 395
DONE ! INDEX_NUM = 396
DONE ! INDEX_NUM = 397
DONE ! INDEX_NUM = 398
DONE ! INDEX_NUM = 399
DONE ! INDEX_NUM = 400
DONE ! INDEX_NUM = 401
DONE ! INDEX_NUM = 402
DONE ! INDEX_NUM = 403
DONE ! INDEX_NUM = 404
DONE ! INDEX_NUM = 405
DONE ! INDEX_NUM = 406
DONE ! INDEX_NUM = 407
DONE ! INDEX_NUM = 408
DONE ! INDEX_NUM = 409
DONE ! INDEX_NUM = 410
DONE ! INDEX_NUM = 411
DONE ! INDEX_NUM = 412
DONE ! INDEX_NUM = 413
DONE ! INDEX_NUM = 414
DONE ! INDEX_NUM = 415
DONE ! INDEX_NUM = 416
DONE ! INDEX_NUM = 417
DONE ! INDEX_NUM = 418
DONE ! INDEX_NUM = 419
DONE ! INDEX_NUM = 420
DONE ! INDEX_NUM = 421
DONE ! INDEX_NUM = 422
DONE ! INDEX_NUM = 423
DONE ! INDEX_NUM = 424
DONE ! INDEX_NUM = 425
DONE ! INDEX_NUM = 426
DONE ! INDEX_NUM = 427
DONE ! INDEX_NUM = 428
DONE ! INDEX_NUM = 429
DONE ! INDEX_NUM = 430
DONE ! INDEX_NUM = 431
DONE ! INDEX_NUM = 432
DONE ! INDEX_NUM = 433
DONE ! INDEX_NUM = 434
DONE ! INDEX_NUM = 435
DONE ! INDEX_NUM = 436
DONE ! INDEX_NUM = 437
DONE ! INDEX_NUM = 438
DONE ! INDEX_NUM = 439
DONE ! INDEX_NUM = 440
DONE ! INDEX_NUM = 441
DONE ! INDEX_NUM = 442
DONE ! INDEX_NUM = 443
DONE ! INDEX_NUM = 444
DONE ! INDEX_NUM = 445
DONE ! INDEX_NUM = 446
DONE ! INDEX_NUM = 447
DONE ! INDEX_NUM = 448
DONE ! INDEX_NUM = 449
DONE ! INDEX_NUM = 450
DONE ! INDEX_NUM = 451
DONE ! INDEX_NUM = 452
DONE ! INDEX_NUM = 453
DONE ! INDEX_NUM = 454
DONE ! INDEX_NUM = 455
DONE ! INDEX_NUM = 456
DONE ! INDEX_NUM = 457
DONE ! INDEX_NUM = 458
DONE ! INDEX_NUM = 459
DONE ! INDEX_NUM = 460
DONE ! INDEX_NUM = 461
DONE ! INDEX_NUM = 462
DONE ! INDEX_NUM = 463
DONE ! INDEX_NUM = 464
DONE ! INDEX_NUM = 465
DONE ! INDEX_NUM = 466
DONE ! INDEX_NUM = 467
DONE ! INDEX_NUM = 468
DONE ! INDEX_NUM = 469
DONE ! INDEX_NUM = 470
DONE ! INDEX_NUM = 471
DONE ! INDEX_NUM = 472
DONE ! INDEX_NUM = 473
DONE ! INDEX_NUM = 474
DONE ! INDEX_NUM = 475
DONE ! INDEX_NUM = 476
DONE ! INDEX_NUM = 477
DONE ! INDEX_NUM = 478
DONE ! INDEX_NUM = 479
DONE ! INDEX_NUM = 480
DONE ! INDEX_NUM = 481
DONE ! INDEX_NUM = 482
DONE ! INDEX_NUM = 483
DONE ! INDEX_NUM = 484
DONE ! INDEX_NUM = 485
DONE ! INDEX_NUM = 486
DONE ! INDEX_NUM = 487
DONE ! INDEX_NUM = 488
DONE ! INDEX_NUM = 489
DONE ! INDEX_NUM = 490
DONE ! INDEX_NUM = 491
DONE ! INDEX_NUM = 492
DONE ! INDEX_NUM = 493
DONE ! INDEX_NUM = 494
DONE ! INDEX_NUM = 495
DONE ! INDEX_NUM = 496
DONE ! INDEX_NUM = 497
DONE ! INDEX_NUM = 498
DONE ! INDEX_NUM = 499
DONE ! INDEX_NUM = 500
DONE ! INDEX_NUM = 501
DONE ! INDEX_NUM = 502
DONE ! INDEX_NUM = 503
DONE ! INDEX_NUM = 504
DONE ! INDEX_NUM = 505
DONE ! INDEX_NUM = 506
DONE ! INDEX_NUM = 507
DONE ! INDEX_NUM = 508
DONE ! INDEX_NUM = 509
DONE ! INDEX_NUM = 510
DONE ! INDEX_NUM = 511
DONE ! INDEX_NUM = 512
DONE ! INDEX_NUM = 513
DONE ! INDEX_NUM = 514
DONE ! INDEX_NUM = 515
DONE ! INDEX_NUM = 516
DONE ! INDEX_NUM = 517
DONE ! INDEX_NUM = 518
DONE ! INDEX_NUM = 519
DONE ! INDEX_NUM = 520
DONE ! INDEX_NUM = 521
DONE ! INDEX_NUM = 522
DONE ! INDEX_NUM = 523
DONE ! INDEX_NUM = 524
DONE ! INDEX_NUM = 525
DONE ! INDEX_NUM = 526
DONE ! INDEX_NUM = 527
DONE ! INDEX_NUM = 528
DONE ! INDEX_NUM = 529
DONE ! INDEX_NUM = 530
DONE ! INDEX_NUM = 531
DONE ! INDEX_NUM = 532
DONE ! INDEX_NUM = 533
DONE ! INDEX_NUM = 534
DONE ! INDEX_NUM = 535
DONE ! INDEX_NUM = 536
DONE ! INDEX_NUM = 537
DONE ! INDEX_NUM = 538
DONE ! INDEX_NUM = 539
DONE ! INDEX_NUM = 540
DONE ! INDEX_NUM = 541
DONE ! INDEX_NUM = 542
DONE ! INDEX_NUM = 543
DONE ! INDEX_NUM = 544
DONE ! INDEX_NUM = 545
DONE ! INDEX_NUM = 546
DONE ! INDEX_NUM = 547
DONE ! INDEX_NUM = 548
DONE ! INDEX_NUM = 549
DONE ! INDEX_NUM = 550
DONE ! INDEX_NUM = 551
DONE ! INDEX_NUM = 552
DONE ! INDEX_NUM = 553
DONE ! INDEX_NUM = 554
DONE ! INDEX_NUM = 555
DONE ! INDEX_NUM = 556
DONE ! INDEX_NUM = 557
DONE ! INDEX_NUM = 558
DONE ! INDEX_NUM = 559
DONE ! INDEX_NUM = 560
DONE ! INDEX_NUM = 561
DONE ! INDEX_NUM = 562
DONE ! INDEX_NUM = 563
DONE ! INDEX_NUM = 564
DONE ! INDEX_NUM = 565
DONE ! INDEX_NUM = 566
DONE ! INDEX_NUM = 567
DONE ! INDEX_NUM = 568
DONE ! INDEX_NUM = 569
DONE ! INDEX_NUM = 570
DONE ! INDEX_NUM = 571
DONE ! INDEX_NUM = 572
DONE ! INDEX_NUM = 573
DONE ! INDEX_NUM = 574
DONE ! INDEX_NUM = 575
DONE ! INDEX_NUM = 576
DONE ! INDEX_NUM = 577
DONE ! INDEX_NUM = 578
DONE ! INDEX_NUM = 579
DONE ! INDEX_NUM = 580
DONE ! INDEX_NUM = 581
DONE ! INDEX_NUM = 582
DONE ! INDEX_NUM = 583
DONE ! INDEX_NUM = 584
DONE ! INDEX_NUM = 585
DONE ! INDEX_NUM = 586
DONE ! INDEX_NUM = 587
DONE ! INDEX_NUM = 588
DONE ! INDEX_NUM = 589
DONE ! INDEX_NUM = 590
DONE ! INDEX_NUM = 591
DONE ! INDEX_NUM = 592
DONE ! INDEX_NUM = 593
DONE ! INDEX_NUM = 594
DONE ! INDEX_NUM = 595
DONE ! INDEX_NUM = 596
DONE ! INDEX_NUM = 597
DONE ! INDEX_NUM = 598
DONE ! INDEX_NUM = 599
DONE ! INDEX_NUM = 600
DONE ! INDEX_NUM = 601
DONE ! INDEX_NUM = 602
DONE ! INDEX_NUM = 603
DONE ! INDEX_NUM = 604
DONE ! INDEX_NUM = 605
DONE ! INDEX_NUM = 606
DONE ! INDEX_NUM = 607
DONE ! INDEX_NUM = 608
DONE ! INDEX_NUM = 609
DONE ! INDEX_NUM = 610
DONE ! INDEX_NUM = 611
DONE ! INDEX_NUM = 612
DONE ! INDEX_NUM = 613
DONE ! INDEX_NUM = 614
DONE ! INDEX_NUM = 615
DONE ! INDEX_NUM = 616
DONE ! INDEX_NUM = 617
DONE ! INDEX_NUM = 618
DONE ! INDEX_NUM = 619
DONE ! INDEX_NUM = 620
DONE ! INDEX_NUM = 621
DONE ! INDEX_NUM = 622
DONE ! INDEX_NUM = 623
DONE ! INDEX_NUM = 624
DONE ! INDEX_NUM = 625
DONE ! INDEX_NUM = 626
DONE ! INDEX_NUM = 627
DONE ! INDEX_NUM = 628
DONE ! INDEX_NUM = 629
DONE ! INDEX_NUM = 630
DONE ! INDEX_NUM = 631
DONE ! INDEX_NUM = 632
DONE ! INDEX_NUM = 633
DONE ! INDEX_NUM = 634
DONE ! INDEX_NUM = 635
DONE ! INDEX_NUM = 636
DONE ! INDEX_NUM = 637
DONE ! INDEX_NUM = 638
DONE ! INDEX_NUM = 639
DONE ! INDEX_NUM = 640
DONE ! INDEX_NUM = 641
DONE ! INDEX_NUM = 642
DONE ! INDEX_NUM = 643
DONE ! INDEX_NUM = 644
DONE ! INDEX_NUM = 645
DONE ! INDEX_NUM = 646
DONE ! INDEX_NUM = 647
DONE ! INDEX_NUM = 648
DONE ! INDEX_NUM = 649
DONE ! INDEX_NUM = 650
DONE ! INDEX_NUM = 651
DONE ! INDEX_NUM = 652
DONE ! INDEX_NUM = 653
DONE ! INDEX_NUM = 654
DONE ! INDEX_NUM = 655
DONE ! INDEX_NUM = 656
DONE ! INDEX_NUM = 657
DONE ! INDEX_NUM = 658
DONE ! INDEX_NUM = 659
DONE ! INDEX_NUM = 660
DONE ! INDEX_NUM = 661
DONE ! INDEX_NUM = 662
DONE ! INDEX_NUM = 663
DONE ! INDEX_NUM = 664
DONE ! INDEX_NUM = 665
DONE ! INDEX_NUM = 666
DONE ! INDEX_NUM = 667
DONE ! INDEX_NUM = 668
DONE ! INDEX_NUM = 669
DONE ! INDEX_NUM = 670
DONE ! INDEX_NUM = 671
DONE ! INDEX_NUM = 672
DONE ! INDEX_NUM = 673
DONE ! INDEX_NUM = 674
DONE ! INDEX_NUM = 675
DONE ! INDEX_NUM = 676
DONE ! INDEX_NUM = 677
DONE ! INDEX_NUM = 678
DONE ! INDEX_NUM = 679
DONE ! INDEX_NUM = 680
DONE ! INDEX_NUM = 681
DONE ! INDEX_NUM = 682
DONE ! INDEX_NUM = 683
DONE ! INDEX_NUM = 684
DONE ! INDEX_NUM = 685
DONE ! INDEX_NUM = 686
DONE ! INDEX_NUM = 687
DONE ! INDEX_NUM = 688
DONE ! INDEX_NUM = 689
DONE ! INDEX_NUM = 690
DONE ! INDEX_NUM = 691
DONE ! INDEX_NUM = 692
DONE ! INDEX_NUM = 693
DONE ! INDEX_NUM = 694
DONE ! INDEX_NUM = 695
DONE ! INDEX_NUM = 696
DONE ! INDEX_NUM = 697
DONE ! INDEX_NUM = 698
DONE ! INDEX_NUM = 699
DONE ! INDEX_NUM = 700
DONE ! INDEX_NUM = 701
DONE ! INDEX_NUM = 702
DONE ! INDEX_NUM = 703
DONE ! INDEX_NUM = 704
DONE ! INDEX_NUM = 705
DONE ! INDEX_NUM = 706
DONE ! INDEX_NUM = 707
DONE ! INDEX_NUM = 708
DONE ! INDEX_NUM = 709
DONE ! INDEX_NUM = 710
DONE ! INDEX_NUM = 711
DONE ! INDEX_NUM = 712
DONE ! INDEX_NUM = 713
DONE ! INDEX_NUM = 714
DONE ! INDEX_NUM = 715
DONE ! INDEX_NUM = 716
DONE ! INDEX_NUM = 717
DONE ! INDEX_NUM = 718
DONE ! INDEX_NUM = 719
DONE ! INDEX_NUM = 720
DONE ! INDEX_NUM = 721
DONE ! INDEX_NUM = 722
DONE ! INDEX_NUM = 723
DONE ! INDEX_NUM = 724
DONE ! INDEX_NUM = 725
DONE ! INDEX_NUM = 726
DONE ! INDEX_NUM = 727
DONE ! INDEX_NUM = 728
DONE ! INDEX_NUM = 729
DONE ! INDEX_NUM = 730
DONE ! INDEX_NUM = 731
DONE ! INDEX_NUM = 732
DONE ! INDEX_NUM = 733
DONE ! INDEX_NUM = 734
DONE ! INDEX_NUM = 735
DONE ! INDEX_NUM = 736
DONE ! INDEX_NUM = 737
DONE ! INDEX_NUM = 738
DONE ! INDEX_NUM = 739
DONE ! INDEX_NUM = 740
DONE ! INDEX_NUM = 741
DONE ! INDEX_NUM = 742
DONE ! INDEX_NUM = 743
DONE ! INDEX_NUM = 744
DONE ! INDEX_NUM = 745
DONE ! INDEX_NUM = 746
DONE ! INDEX_NUM = 747
DONE ! INDEX_NUM = 748
DONE ! INDEX_NUM = 749
DONE ! INDEX_NUM = 750
DONE ! INDEX_NUM = 751
DONE ! INDEX_NUM = 752
DONE ! INDEX_NUM = 753
DONE ! INDEX_NUM = 754
DONE ! INDEX_NUM = 755
DONE ! INDEX_NUM = 756
DONE ! INDEX_NUM = 757
DONE ! INDEX_NUM = 758
DONE ! INDEX_NUM = 759
DONE ! INDEX_NUM = 760
DONE ! INDEX_NUM = 761
DONE ! INDEX_NUM = 762
DONE ! INDEX_NUM = 763
DONE ! INDEX_NUM = 764
DONE ! INDEX_NUM = 765
DONE ! INDEX_NUM = 766
DONE ! INDEX_NUM = 767
DONE ! INDEX_NUM = 768
DONE ! INDEX_NUM = 769
DONE ! INDEX_NUM = 770
DONE ! INDEX_NUM = 771
DONE ! INDEX_NUM = 772
DONE ! INDEX_NUM = 773
DONE ! INDEX_NUM = 774
DONE ! INDEX_NUM = 775
DONE ! INDEX_NUM = 776
DONE ! INDEX_NUM = 777
DONE ! INDEX_NUM = 778
DONE ! INDEX_NUM = 779
DONE ! INDEX_NUM = 780
DONE ! INDEX_NUM = 781
DONE ! INDEX_NUM = 782
DONE ! INDEX_NUM = 783
DONE ! INDEX_NUM = 784
DONE ! INDEX_NUM = 785
DONE ! INDEX_NUM = 786
DONE ! INDEX_NUM = 787
DONE ! INDEX_NUM = 788
DONE ! INDEX_NUM = 789
DONE ! INDEX_NUM = 790
DONE ! INDEX_NUM = 791
DONE ! INDEX_NUM = 792
DONE ! INDEX_NUM = 793
DONE ! INDEX_NUM = 794
DONE ! INDEX_NUM = 795
DONE ! INDEX_NUM = 796
DONE ! INDEX_NUM = 797
DONE ! INDEX_NUM = 798
DONE ! INDEX_NUM = 799
DONE ! INDEX_NUM = 800
DONE ! INDEX_NUM = 801
DONE ! INDEX_NUM = 802
DONE ! INDEX_NUM = 803
DONE ! INDEX_NUM = 804
DONE ! INDEX_NUM = 805
DONE ! INDEX_NUM = 806
DONE ! INDEX_NUM = 807
DONE ! INDEX_NUM = 808
DONE ! INDEX_NUM = 809
DONE ! INDEX_NUM = 810
DONE ! INDEX_NUM = 811
DONE ! INDEX_NUM = 812
DONE ! INDEX_NUM = 813
DONE ! INDEX_NUM = 814
DONE ! INDEX_NUM = 815
DONE ! INDEX_NUM = 816
DONE ! INDEX_NUM = 817
DONE ! INDEX_NUM = 818
DONE ! INDEX_NUM = 819
DONE ! INDEX_NUM = 820
DONE ! INDEX_NUM = 821
DONE ! INDEX_NUM = 822
DONE ! INDEX_NUM = 823
DONE ! INDEX_NUM = 824
DONE ! INDEX_NUM = 825
DONE ! INDEX_NUM = 826
DONE ! INDEX_NUM = 827
DONE ! INDEX_NUM = 828
DONE ! INDEX_NUM = 829
DONE ! INDEX_NUM = 830
DONE ! INDEX_NUM = 831
DONE ! INDEX_NUM = 832
DONE ! INDEX_NUM = 833
DONE ! INDEX_NUM = 834
DONE ! INDEX_NUM = 835
DONE ! INDEX_NUM = 836
DONE ! INDEX_NUM = 837
DONE ! INDEX_NUM = 838
DONE ! INDEX_NUM = 839
DONE ! INDEX_NUM = 840
DONE ! INDEX_NUM = 841
DONE ! INDEX_NUM = 842
DONE ! INDEX_NUM = 843
DONE ! INDEX_NUM = 844
DONE ! INDEX_NUM = 845
DONE ! INDEX_NUM = 846
DONE ! INDEX_NUM = 847
DONE ! INDEX_NUM = 848
DONE ! INDEX_NUM = 849
DONE ! INDEX_NUM = 850
DONE ! INDEX_NUM = 851
DONE ! INDEX_NUM = 852
DONE ! INDEX_NUM = 853
DONE ! INDEX_NUM = 854
DONE ! INDEX_NUM = 855
DONE ! INDEX_NUM = 856
DONE ! INDEX_NUM = 857
DONE ! INDEX_NUM = 858
DONE ! INDEX_NUM = 859
DONE ! INDEX_NUM = 860
DONE ! INDEX_NUM = 861
DONE ! INDEX_NUM = 862
DONE ! INDEX_NUM = 863
DONE ! INDEX_NUM = 864
DONE ! INDEX_NUM = 865
DONE ! INDEX_NUM = 866
DONE ! INDEX_NUM = 867
DONE ! INDEX_NUM = 868
DONE ! INDEX_NUM = 869
DONE ! INDEX_NUM = 870
DONE ! INDEX_NUM = 871
DONE ! INDEX_NUM = 872
DONE ! INDEX_NUM = 873

In [12]:
#(2) 처리 결과 확인하기.
RANDOM_POINT

,rand_point,자치구,행정동_코드,행정동,세대_COUNT,노래연습장_COUNT,당구장_COUNT,PC방_COUNT,금연구역_10m_COUNT,금연구역_50m_COUNT,음식점_외식_COUNT,음식점_회식_COUNT,음식점_카페_COUNT,위도,경도,geometry,SCORE_b,SCORE_s,SCORE_sum
0,0,금천구,1154568000,시흥제2동,0.250891,1,0,0,2,1,9,3,1,37.449962,126.913406,POINT (192337.7432523154 438954.0766042818),2499.000000,-294,2143.000000
1,1,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,11,4,1,37.449964,126.914394,POINT (192425.2336731556 438954.2123132667),2981.000000,-348,2553.000000
2,2,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,11,4,1,37.449939,126.914258,POINT (192413.1979568179 438951.4329210447),2981.000000,-348,2553.000000
3,3,금천구,1154568000,시흥제2동,0.250891,2,0,0,2,1,9,4,1,37.449956,126.913289,POINT (192327.4056526743 438953.4538745985),2535.000000,-296,2182.000000
4,4,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,12,4,1,37.450008,126.913638,POINT (192358.2717906134 438959.210054699),3246.000000,-380,2777.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40286,41191,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.499947,126.953611,POINT (195897.9891959261 444499.2420208962),246.316215,29,200.913892
40287,41192,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.500272,126.953683,POINT (195904.4341447904 444535.2696354929),246.316215,29,200.913892
40288,41193,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.500105,126.953733,POINT (195908.8060317755 444516.8050831873),246.316215,29,200.913892
40289,41194,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,1,0,0,37.500540,126.953708,POINT (195906.6493213855 444565.0878704682),510.596215,6,465.193892
40290,41195,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.499826,126.953583,POINT (195895.5612148321 444485.8452144368),246.316215,29,200.913892

In [15]:
#04. SCORE_b와 SCORE_s 합산하기
#(1)
RANDOM_POINT['SCORE_sum'] = (RANDOM_POINT['SCORE_b'] + RANDOM_POINT['SCORE_s'])/2

#(2)
RANDOM_POINT

,rand_point,자치구,행정동_코드,행정동,세대_COUNT,노래연습장_COUNT,당구장_COUNT,PC방_COUNT,금연구역_10m_COUNT,금연구역_50m_COUNT,음식점_외식_COUNT,음식점_회식_COUNT,음식점_카페_COUNT,위도,경도,geometry,SCORE_b,SCORE_s,SCORE_sum
0,0,금천구,1154568000,시흥제2동,0.250891,1,0,0,2,1,9,3,1,37.449962,126.913406,POINT (192337.7432523154 438954.0766042818),2499.000000,-294,1102.500000
1,1,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,11,4,1,37.449964,126.914394,POINT (192425.2336731556 438954.2123132667),2981.000000,-348,1316.500000
2,2,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,11,4,1,37.449939,126.914258,POINT (192413.1979568179 438951.4329210447),2981.000000,-348,1316.500000
3,3,금천구,1154568000,시흥제2동,0.250891,2,0,0,2,1,9,4,1,37.449956,126.913289,POINT (192327.4056526743 438953.4538745985),2535.000000,-296,1119.500000
4,4,금천구,1154568000,시흥제2동,0.250891,0,0,0,3,0,12,4,1,37.450008,126.913638,POINT (192358.2717906134 438959.210054699),3246.000000,-380,1433.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40286,41191,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.499947,126.953611,POINT (195897.9891959261 444499.2420208962),246.316215,29,137.658107
40287,41192,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.500272,126.953683,POINT (195904.4341447904 444535.2696354929),246.316215,29,137.658107
40288,41193,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.500105,126.953733,POINT (195908.8060317755 444516.8050831873),246.316215,29,137.658107
40289,41194,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,1,0,0,37.500540,126.953708,POINT (195906.6493213855 444565.0878704682),510.596215,6,258.298107
40290,41195,동작구,1159053000,상도제1동,0.968186,0,0,0,0,0,0,0,0,37.499826,126.953583,POINT (195895.5612148321 444485.8452144368),246.316215,29,137.658107

In [16]:
#(3) 처리 결과 저장하기. 
RANDOM_POINT.to_excel('temp_file.xlsx', index=False)