In [2]:
#2021.07.10. SAT
#Team_2030
 
## NLP
#00. 패키지 호출
import numpy as np 
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [20]:
#01. 뉴스기사 자연어 처리하기. 
#(1) 데이터셋 불러오기. 
article = pd.read_excel('../data/text_data/article_crawling.xlsx')

#(2) 데이터셋 살펴보기. 
article

,article_date,article_num_date,company_name,headline,contents
0,2018. 2. 1.,0,WIRED,What is Bitcoin? The Complete WIRED Guide,Bitcoin is a digital currency. Like other curr...
1,2018. 2. 1.,0,Mint,Budget 2018: Bitcoin prices slump to lowest th...,New York/Hong Kong: Bitcoin slumped to its low...
2,2018. 2. 1.,0,Bloomberg.com,India Turns Against Bitcoin But Embraces Block...,“The government does not consider cryptocurren...
3,2018. 2. 1.,0,The Johns Hopkins News-Letter,"What is Bitcoin, and why is it so popular?",PUBLIC DOMAIN The value of Bitcoin had surged ...
4,2018. 2. 1.,0,CTV News,"If you sold or used Bitcoin last year, the CRA...","The price of Bitcoin shot above US$19,000 in m..."
...,...,...,...,...,...
11953,3일 전,1251,Cointelegraph,BlockFi starts shipping Visa-backed Bitcoin re...,New York-based crypto loans and savings startu...
11954,2일 전,1251,Bloomberg.com,A Bitcoin ETF Would Be Good for Investors and ...,The Securities and Exchange Commission faces a...
11955,2일 전,1251,Analytics Insight,"In the Mid 2021, Bitcoin's Year So Far was a R...",Bitcoin's year so far taught crypto investors ...
11956,3일 전,1251,Bitcoinist,Is New York's Seneca Lake Too Hot Because Of B...,And they ran with the apparent rising temperat...
11957,2일 전,1251,Newsweek,'Bitcoin King' Arrested in Alleged $300M Fraud...,Oliveira reported a bitcoin hack on his compan...

In [21]:
#(3) 데이터셋 정보 확인하기. 
article.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11958 entries, 0 to 11957
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   article_date      11958 non-null  object
 1   article_num_date  11958 non-null  int64
 2   company_name      11958 non-null  object
 3   headline          11958 non-null  object
 4   contents          11958 non-null  object
dtypes: int64(1), object(4)
memory usage: 467.2+ KB

In [22]:
#(4) 데이터셋 결측치 확인하기. 
article.isna().sum()

article_date        0
article_num_date    0
company_name        0
headline            0
contents            0
dtype: int64

In [23]:
#02. 자연어 처리하기.  
#(1) vader 객체 지정하기. 
vader = SentimentIntensityAnalyzer()

#(2) sample로 작동 확인하기. 
sample = """
The bear market in bitcoin isn’t letting up, as the original cryptoaⓙsset has fallen to its lowest level in more than two months. What’s more, other digital assets like ripple and bitcoin cash have tumbled furtherdown more than 70% from their peaks as regulatory scrutiny of the budding sector increases around the world.
"""
vader.polarity_scores(sample)

{'neg': 0.085, 'neu': 0.802, 'pos': 0.113, 'compound': 0.1689}

In [27]:
#(3) headline 전부 감성분석하기. 
hl_senti_score_list= []
for i in range(len(article)) :
    hl_senti_score = vader.polarity_scores(article['headline'][i])['compound'] 
    hl_senti_score_list.append(hl_senti_score)

#(4) 감성분석 점수 확인하기. 
hl_senti_score_list[:10]

[0.0, -0.3818, 0.0, 0.5598, 0.0, 0.0, -0.3384, 0.0, -0.4019, 0.4215]

In [33]:
#(5) contents 전부 감성분석하기. 
cts_senti_score_list= []
for i in range(len(article)) :
    cts_senti_score = vader.polarity_scores(article['contents'][i])['compound'] 
    cts_senti_score_list.append(cts_senti_score)

#(6) 감성분석 점수 확인하기. 
cts_senti_score_list[:10]

[0.6249, -0.25, -0.0951, 0.6369, 0.4588, 0.6124, 0.0, 0.0, 0.2263, 0.0]

In [34]:
#(5) 데이터프레임에 결합하기. 
article['hl_senti_score'] = hl_senti_score_list
article['cts_senti_score'] = cts_senti_score_list

#(6) 결합 확인하기. 
article

,article_date,article_num_date,company_name,headline,contents,hl_senti_score,cts_senti_score
0,2018. 2. 1.,0,WIRED,What is Bitcoin? The Complete WIRED Guide,Bitcoin is a digital currency. Like other curr...,0.0000,0.6249
1,2018. 2. 1.,0,Mint,Budget 2018: Bitcoin prices slump to lowest th...,New York/Hong Kong: Bitcoin slumped to its low...,-0.3818,-0.2500
2,2018. 2. 1.,0,Bloomberg.com,India Turns Against Bitcoin But Embraces Block...,“The government does not consider cryptocurren...,0.0000,-0.0951
3,2018. 2. 1.,0,The Johns Hopkins News-Letter,"What is Bitcoin, and why is it so popular?",PUBLIC DOMAIN The value of Bitcoin had surged ...,0.5598,0.6369
4,2018. 2. 1.,0,CTV News,"If you sold or used Bitcoin last year, the CRA...","The price of Bitcoin shot above US$19,000 in m...",0.0000,0.4588
...,...,...,...,...,...,...,...
11953,3일 전,1251,Cointelegraph,BlockFi starts shipping Visa-backed Bitcoin re...,New York-based crypto loans and savings startu...,0.6908,0.8402
11954,2일 전,1251,Bloomberg.com,A Bitcoin ETF Would Be Good for Investors and ...,The Securities and Exchange Commission faces a...,0.4404,0.4588
11955,2일 전,1251,Analytics Insight,"In the Mid 2021, Bitcoin's Year So Far was a R...",Bitcoin's year so far taught crypto investors ...,0.0000,0.7397
11956,3일 전,1251,Bitcoinist,Is New York's Seneca Lake Too Hot Because Of B...,And they ran with the apparent rising temperat...,0.0000,-0.1779
11957,2일 전,1251,Newsweek,'Bitcoin King' Arrested in Alleged $300M Fraud...,Oliveira reported a bitcoin hack on his compan...,-0.7845,-0.6956

In [35]:
#03. article 데이터프레임 저장하기. 
article.to_excel('../data/text_data/article_senti_score.xlsx', index=False)